// book 13 manifest: chapter registry used by cross references and stubs
#let kddbook = (
  num: 13,
  volume: false,
  title: "knowledge discovery",
  meta: (
    title: "knowledge discovery",
    subtitle: "from preprocessing to self-organizing maps in c23, with a go and duckdb capstone",
    author: "Mr. Raheliosol",
    version: "2.0",
    volume-label: "book 13",
  ),
  chapters: (
    (id: "process", num: 1, title: "the knowledge discovery process"),
    (id: "cleaning", num: 2, title: "data cleaning and imputation"),
    (id: "binning", num: 3, title: "binning, smoothing, and discretization"),
    (id: "normalize", num: 4, title: "normalization and standardization"),
    (id: "distance", num: 5, title: "distance metrics"),
    (id: "similarity", num: 6, title: "similarity measures"),
    (id: "sampling", num: 7, title: "sampling"),
    (id: "features", num: 8, title: "feature selection and chi-square"),
    (id: "pca", num: 9, title: "principal component analysis"),
    (id: "wavelet", num: 10, title: "the haar wavelet transform"),
    (id: "olap", num: 11, title: "data cubes and olap"),
    (id: "regression", num: 12, title: "simple linear regression"),
    (id: "id3", num: 13, title: "decision trees: id3"),
    (id: "cart", num: 14, title: "decision trees: cart and continuous splits"),
    (id: "rules", num: 15, title: "rules from trees and sequential covering"),
    (id: "pruning", num: 16, title: "overfitting and pruning"),
    (id: "evaluation", num: 17, title: "classifier evaluation"),
    (id: "roc", num: 18, title: "roc and auc"),
    (id: "bayes", num: 19, title: "naive bayes"),
    (id: "knn", num: 20, title: "nearest neighbor"),
    (id: "ann", num: 21, title: "neural networks"),
    (id: "svm", num: 22, title: "support vector machines"),
    (id: "ensembles", num: 23, title: "bagging, boosting, and random forests"),
    (id: "imbalance", num: 24, title: "class imbalance"),
    (id: "apriori", num: 25, title: "levelwise apriori"),
    (id: "vector", num: 26, title: "vector apriori"),
    (id: "maximal", num: 27, title: "maximal itemsets and rule generation"),
    (id: "fpgrowth", num: 28, title: "fp-growth"),
    (id: "interesting", num: 29, title: "interestingness, multilevel, and quantitative rules"),
    (id: "sequential", num: 30, title: "sequential patterns"),
    (id: "kmeans", num: 31, title: "k-means"),
    (id: "hierarchical", num: 32, title: "hierarchical clustering"),
    (id: "dbscan", num: 33, title: "dbscan"),
    (id: "validation", num: 34, title: "cluster validation"),
    (id: "cure", num: 35, title: "cure and chameleon"),
    (id: "spectral", num: 36, title: "spectral clustering"),
    (id: "anomaly", num: 37, title: "statistical anomaly detection"),
    (id: "lof", num: 38, title: "proximity and density anomalies"),
    (id: "hypothesis", num: 39, title: "hypothesis testing and p-values"),
    (id: "fdr", num: 40, title: "multiple testing: bonferroni and fdr"),
    (id: "rough", num: 41, title: "rough sets: indiscernibility and approximations"),
    (id: "reducts", num: 42, title: "rough sets: dependency and reducts"),
    (id: "discernibility", num: 43, title: "rough sets: discernibility and rule induction"),
    (id: "som", num: 44, title: "self-organizing maps"),
    (id: "somanalysis", num: 45, title: "som analysis and visualization"),
    (id: "somvariants", num: 46, title: "som variants"),
    (id: "bridge", num: 47, title: "the bridge: c to go"),
    (id: "capstone", num: 48, title: "the capstone: a kdd pipeline on duckdb, with coverage appendices"),
  ),
)
