#import "../../theme/lib.typ": listing, snippet, callout, diagram, cdraw, xref-to

= numpy

This chapter teaches numpy before anything downstream uses it. The version is
the first fact: numpy 2.5.3, pinned in `books/python/requirements.txt`,
installed into the gate's venv, and asserted from inside the first sample,
because search engines still surface numpy 2.x answers by volume and the
behavior this chapter pins changed across that line. #xref-to("python",
"capstone2") builds its analytics leg on the arrays introduced here, and
#xref-to("python", "pandas") builds its frames on the same arrays next
chapter. The float semantics underneath are the ones
#xref-to("python", "numerics") already pinned: binary64, the neighbor
double, and `math.isclose`. The stdlib chapter handles scalars one at a
time; numpy handles a million of them as one buffer, and every claim below
is an ok line in the four samples, 38 in total, or a sentence quoted from
the numpy 2.5 manual fetched 2026-09-12.

== the ndarray

An ndarray is one block of memory plus the metadata that walks it. The
manual defines the walking triple in three lines: `ndarray.shape`, "Tuple
of array dimensions", `ndarray.strides`, "Tuple of bytes to step in each
dimension when traversing an array", and `ndarray.itemsize`, "Length of
one array element in bytes". A 3 by 4 grid of int32 pins all three at
once, strides `(16, 4)`, four bytes per element and sixteen to jump a row,
and `asfortranarray` walks the same numbers the other way, `(4, 12)`:

#listing("python/samples/src/Ch24/ndarray.py", first: 68, last: 74, caption: [the chapter contract: the interpreter pin, then the numpy 2.5.3 pin asserted in-sample])

#listing("python/samples/src/Ch24/ndarray.py", first: 8, last: 18, caption: [shape, dtype, strides, itemsize, nbytes, size, ndim pinned as one tuple])

#listing("python/samples/src/Ch24/ndarray.py", first: 21, last: 31, caption: [fortran order flips the strides, and the four everyday constructors with the dtype each was asked for])

The constructors are chosen by shape: `zeros` and `ones` take a shape,
`arange` takes a step like `range`, and `linspace` takes a count and
includes both endpoints, 0.0 through 1.0 in five values. The deeper half
of the section is the view and copy split, and the manual states it as a
rule, not a tendency: "All arrays generated by basic slicing are always
views of the original array", while "Advanced indexing always returns a
copy of the data (contrast with basic slicing that returns a view)". The
sample asserts both halves on one owner:

#listing("python/samples/src/Ch24/ndarray.py", first: 34, last: 55, caption: [five index expressions that stay views, five that own their memory, and shares_memory as the judge])

#listing("python/samples/src/Ch24/ndarray.py", first: 58, last: 65, caption: [a view write lands in the owner, a copy write never does])

The `base` attribute answers who owns the buffer, and the sample uses a
literal `np.array` as its owner on purpose: `base` reports the memory
owner, not the last expression. Slicing an array that is itself a reshape
reports the original buffer, not the intermediate, so `base` is for
ownership questions and `np.shares_memory` for relation questions.

#diagram([the ndarray as memory: one buffer, a shape and strides that walk it, and the two doors out of it], length: 13pt, {
  let cell(x, y, t, fill: luma(235)) = {
    cdraw.rect((x, y), (x + 2.2, y + 1.0), fill: fill, radius: 0.02)
    cdraw.content((x + 1.1, y + 0.5), t, wrap: text.with(size: 6pt))
  }
  let bx = 4.4
  for r in range(3) {
    for c in range(4) {
      cell(bx + c * 2.4, 8.4 - r * 1.2, [int32], fill: if calc.even(r + c) { luma(235) } else { luma(250) })
    }
  }
  cdraw.content((9.2, 9.7), [one buffer, 48 bytes, walked as a 3 by 4 grid], wrap: text.with(size: 6.5pt))
  cdraw.line((14.8, 8.6), (14.8, 7.4), stroke: luma(60), mark: (end: ">"))
  cdraw.content((16.6, 8.0), [+16 bytes #linebreak() per row], wrap: text.with(size: 6pt))
  cdraw.line((4.8, 5.2), (7.2, 5.2), stroke: luma(60), mark: (end: ">"))
  cdraw.content((9.8, 5.2), [+4 bytes per column], wrap: text.with(size: 6pt))
  cdraw.content((18.2, 6.6), [strides (16, 4), #linebreak() fortran walks #linebreak() (4, 12)], wrap: text.with(size: 6pt, fill: luma(100)))
  let door(x, t, sub) = {
    cdraw.rect((x, 1.4), (x + 7.4, 4.0), fill: luma(235), radius: 0.02)
    cdraw.content((x + 3.7, 3.2), t, wrap: text.with(size: 6pt))
    cdraw.content((x + 3.7, 2.1), sub, wrap: text.with(size: 6pt, fill: luma(100)))
  }
  door(2.4, [slicing, reshape, #linebreak() transpose, ravel], [views, base is the owner])
  door(12.2, [fancy indexing, masks, #linebreak() astype, copy], [copies, own their memory])
  cdraw.line((6.1, 4.9), (6.1, 4.0), stroke: luma(100), mark: (end: ">"))
  cdraw.line((15.9, 4.9), (15.9, 4.0), stroke: luma(100), mark: (end: ">"))
  cdraw.content((11.0, 0.6), [a view write lands in the owner, a copy write never does], wrap: text.with(size: 6.5pt, fill: luma(100)))
})

== vectorization and broadcasting

The before and after is one loop. The manual sells broadcasting as exactly
that: "Broadcasting provides a means of vectorizing array operations so
that looping occurs in C instead of Python." The sample runs both forms on
the same four temperatures and asserts they agree to the last bit, the
python loop appending one division at a time, the ufunc expression making
one pass over the buffer:

#listing("python/samples/src/Ch24/broadcast.py", first: 6, last: 11, caption: [the loop and the ufunc expression, asserted equal element for element])

The shape rules are three sentences. "When operating on two arrays, NumPy
compares their shapes element-wise. It starts with the trailing (i.e.
rightmost) dimension and works its way left." Then the compatibility test:
"Two dimensions are compatible when 1. they are equal, or 2. one of them
is 1", and when neither holds, "a `ValueError: operands could not be
broadcast together` exception is thrown, indicating that the arrays have
incompatible shapes". The failing message quotes both shapes verbatim on
this machine, `(2,3)` against `(4,)`:

#listing("python/samples/src/Ch24/broadcast.py", first: 14, last: 28, caption: [a (4, 1) column plus a (3,) row stretches into the full (4, 3) grid])

#listing("python/samples/src/Ch24/broadcast.py", first: 31, last: 39, caption: [the mismatch quotes its shapes in the error text])

#listing("python/samples/src/Ch24/broadcast.py", first: 42, last: 51, caption: [broadcast_to stretches without copying, and the result is read-only])

Reductions give the axis its meaning. `sum(axis=0)` folds down the
columns, `sum(axis=1)` folds along the rows, `axis=None` flattens first,
negative indices count from the last axis, and `keepdims` keeps the folded
axis at size 1 so a downstream broadcast still lines up. The dtype rules
come along for free and are worth pinning: an int32 array sums to int64
and means to float64, a float32 array stays float32 through its sum:

#listing("python/samples/src/Ch24/broadcast.py", first: 105, last: 117, caption: [axis 0, axis 1, axis None, axis -1, and keepdims, each with its result pinned])

#listing("python/samples/src/Ch24/broadcast.py", first: 54, last: 60, caption: [int32 sums to int64 and means to float64, float32 keeps its dtype])

The empty case splits by identity. An empty float array sums to 0.0, the
identity for addition, and refuses a max with "zero-size array to
reduction operation maximum which has no identity":

#listing("python/samples/src/Ch24/broadcast.py", first: 63, last: 70, caption: [empty sums to the identity, empty max refuses with the identity message])

#diagram([before and after: one python loop per element against one ufunc pass, and the three sentence shape rule under it], length: 13pt, {
  let box(x, y, w, h, t, fill: luma(235)) = {
    cdraw.rect((x, y), (x + w, y + h), fill: fill, radius: 0.02)
    cdraw.content((x + w / 2, y + h / 2), t, wrap: text.with(size: 6pt))
  }
  cdraw.content((5.0, 8.9), [the python loop], wrap: text.with(size: 6.5pt))
  cdraw.content((16.2, 8.9), [the ufunc call], wrap: text.with(size: 6.5pt))
  box(0.6, 6.9, 8.8, 1.5, [for c in temps: append(...)])
  box(0.6, 4.9, 8.8, 1.5, [bytecode dispatch, #linebreak() one call per element])
  box(12.0, 6.9, 8.8, 1.5, [`temps * 9.0 / 5.0 - 32.0`])
  box(12.0, 4.9, 8.8, 1.5, [one typed loop in C, #linebreak() over the whole buffer])
  cdraw.line((9.4, 7.6), (12.0, 7.6), stroke: luma(100), mark: (end: ">"))
  cdraw.content((10.7, 8.2), [same #linebreak() values], wrap: text.with(size: 6pt, fill: luma(100)))
  box(0.6, 2.7, 8.8, 1.2, [shapes compared right to left], fill: luma(250))
  box(10.0, 2.7, 5.4, 1.2, [equal, or one is 1])
  box(16.0, 2.7, 5.6, 1.2, [else ValueError])
  cdraw.line((9.4, 3.3), (10.0, 3.3), stroke: luma(100), mark: (end: ">"))
  cdraw.line((15.4, 3.3), (16.0, 3.3), stroke: luma(100), mark: (end: ">"))
  cdraw.content((11.0, 1.3), [(4, 1) plus (3,) gives (4, 3), `broadcast_to` gives it free and read-only], wrap: text.with(size: 6.5pt, fill: luma(100)))
})

== fancy indexing and masks

Selection becomes data dependent here, and the indexer's type decides the
door. A boolean mask keeps the elements where it is true, masks combine
with `&` and `|` elementwise, and an integer index array may repeat or
reorder indices freely. `np.where` plays two roles: three arguments make
it the vector conditional, one argument makes it `nonzero`. The matrix
case is worth seeing once, a boolean mask on a 3 by 4 grid returns the
flat survivors, and paired index arrays select points, `(2, 1)` and
`(0, 3)`:

#listing("python/samples/src/Ch24/masks.py", first: 6, last: 14, caption: [masks select, combine with elementwise and, and invert])

#listing("python/samples/src/Ch24/masks.py", first: 17, last: 27, caption: [integer arrays repeat indices, where picks values, nonzero and argmax locate])

#listing("python/samples/src/Ch24/masks.py", first: 80, last: 91, caption: [a mask on a matrix flattens, paired arrays select points, one axis may stay basic])

The assignment side has the one trap in this chapter. `a[idx] += 1` with a
repeated index gathers, adds, and scatters buffered, so the second write
to the same slot overwrites the first instead of accumulating: index 0
appears twice in `idx` and the count lands on 1, not 2. `np.add.at` is the
unbuffered ufunc method made for exactly this, and it counts 2:

#listing("python/samples/src/Ch24/masks.py", first: 30, last: 42, caption: [buffered fancy scatter loses repeats, add.at accumulates them])

Missing data gets its own ufuncs rather than sentinel tricks: `isfinite`
and `isnan` classify, `nansum` and `nanmean` skip the holes, and `clip`
pins a range in one call:

#listing("python/samples/src/Ch24/masks.py", first: 45, last: 52, caption: [isfinite and isnan classify, nanmean averages around the hole])

#callout("pitfall", "the buffered scatter loses repeats", [
  `a[idx] += 1` is sugar for gather, add, scatter, and the scatter step
  writes each slot once per final value, not once per appearance in `idx`.
  When indices repeat and the operation must accumulate, `np.add.at(a,
  idx, 1)` is the documented door. The sample pins the divergent outcomes
  side by side, 1 against 2, so the trap is a red line in the gate rather
  than a war story.
])

#diagram([what the indexer contains decides the door, and assignment through a fancy indexer decides the buffer], length: 13pt, {
  let box(x, y, w, h, t, fill: luma(235)) = {
    cdraw.rect((x, y), (x + w, y + h), fill: fill, radius: 0.02)
    cdraw.content((x + w / 2, y + h / 2), t, wrap: text.with(size: 6pt))
  }
  box(0.6, 7.4, 6.0, 1.4, [the indexer])
  box(9.0, 8.3, 5.4, 1.3, [a slice], fill: luma(250))
  box(9.0, 6.4, 5.4, 1.3, [a bool or int array])
  box(16.4, 8.3, 5.0, 1.3, [a view])
  box(16.4, 6.4, 5.0, 1.3, [a copy])
  cdraw.line((6.6, 8.2), (9.0, 8.9), stroke: luma(100), mark: (end: ">"))
  cdraw.line((6.6, 8.0), (9.0, 7.1), stroke: luma(100), mark: (end: ">"))
  cdraw.line((14.4, 8.9), (16.4, 8.9), stroke: luma(100), mark: (end: ">"))
  cdraw.line((14.4, 7.0), (16.4, 7.0), stroke: luma(100), mark: (end: ">"))
  box(0.6, 3.6, 10.4, 1.4, [a[idx] += 1: gather, add, #linebreak() buffered scatter, repeats lost])
  box(12.4, 3.6, 9.0, 1.4, [np.add.at(a, idx, 1): #linebreak() unbuffered, repeats accumulate])
  cdraw.line((5.8, 6.4), (5.8, 5.0), stroke: luma(100), mark: (end: ">"))
  cdraw.line((16.9, 6.4), (16.9, 5.0), stroke: luma(100), mark: (end: ">"))
  cdraw.content((11.0, 2.2), [where(cond, x, y) is the vector conditional, where(cond) is nonzero], wrap: text.with(size: 6.5pt, fill: luma(100)))
  cdraw.content((11.0, 1.0), [nan aware ufuncs skip the holes instead of guarding around them], wrap: text.with(size: 6.5pt, fill: luma(100)))
})

== dtypes and promotion

Promotion is the numpy 2 line in the sand, specified by NEP 50 and
enforced since 2.0: "We propose to remove all value-based logic and add
special handling for Python scalars to preserve some convenient
behaviors. Python scalars will be considered 'weakly' typed." The
principle behind it, "Values must never influence result type", and the
operating rule, "At no time is the value used to decide the result of
this promotion. The value is only considered when it is converted to the
new dtype; this may raise an error", are both quotable from the nep. In
practice: a python int or float adopts the array's dtype, so an int32
array plus `1` stays int32 and a float32 array plus `1.5` stays float32,
while a kind change goes to the minimum float, float64. A numpy scalar or
a second array is strong: int32 meets int64 and int64 wins, uint8 meets
int8 and the signed result is int16, uint64 meets int64 and the result
is float64, because no integer dtype holds both:

#listing("python/samples/src/Ch24/dtypes.py", first: 6, last: 12, caption: [python scalars are weak, the array dtype survives, kind changes go float64])

#listing("python/samples/src/Ch24/dtypes.py", first: 15, last: 21, caption: [numpy scalars are strong, and uint64 with int64 lands in float64])

The error side is the point of the design, errors over silent casting.
An int8 array plus `256` raises `OverflowError: Python integer 256 out
of bounds for int8`. A uint64 array plus `-1` refuses the same way.
Writing `2**40` into an int32 slot raises "Python int too large to
convert to C long", the windows flavor of the boundary, where a C long
is four bytes. In place operations keep their dtype when they can, a
float32 array absorbs `+= 1.5`, and refuse with the same_kind casting
message when they cannot, an int32 array plus `1.5` in place:

#listing("python/samples/src/Ch24/dtypes.py", first: 24, last: 39, caption: [three overflow refusals with the exact message text, never a silent wrap])

#listing("python/samples/src/Ch24/dtypes.py", first: 42, last: 50, caption: [in place keeps float32, int32 in place refuses float under same_kind])

One silent case survives, and it is worth knowing which one. A weak
python scalar that fits the dtype is converted with no complaint, so a
uint8 array holding 250 plus `10` wraps to 4 modulo 256, only the
scalar-on-scalar form warns. The value is bounded by the dtype, not by
the operation, which is the NEP 50 bargain: predictable types, and the
programmer carries the range check.

Strings come in two dtypes. The historical `<U5` fixes the width at
array creation, wasted bytes for short entries, truncation beyond it.
`np.dtypes.StringDType()` is the variable width dtype with a real `None`
for missing entries, and the `np.strings` module carries the ufuncs,
`upper` on either dtype. Adding an int to either is a TypeError, "ufunc
'add' did not contain a loop with signature matching types", because
there is no cast to fall back on:

#listing("python/samples/src/Ch24/dtypes.py", first: 53, last: 70, caption: [fixed U widths, StringDType and its None, np.strings on both, and the no-loop TypeError])

Dates are integer counts with units. The manual: "The date units are
years ('Y'), months ('M'), weeks ('W'), and days ('D'), while the time
units are hours ('h'), minutes ('m'), seconds ('s'), milliseconds
('ms'), and some additional SI-prefix seconds-based units", and for
calendars, "NumPy includes a set of 'busday' (business day) functions".
A week of days builds with `arange`, subtraction yields a timedelta64,
adding a one day timedelta shifts the week, 90 minutes cast to hours
truncates to 1, and monday through friday of the book's reference week
counts 5:

#listing("python/samples/src/Ch24/dtypes.py", first: 73, last: 83, caption: [datetime64 units, timedelta arithmetic, and the business day count])

The pandas handoff closes the chapter. #xref-to("python", "pandas")
stores its text in the str dtype and its numbers in these dtypes, and
`to_numpy` hands the buffer over, which is why the two libraries compose
without copying in the common path.

#diagram([promotion as a matrix: weak python scalars adopt, strong numpy operands negotiate, out of range raises], length: 13pt, {
  let cell(x, y, w, h, t, fill: luma(235)) = {
    cdraw.rect((x, y), (x + w, y + h), fill: fill, radius: 0.02)
    cdraw.content((x + w / 2, y + h / 2), t, wrap: text.with(size: 6pt))
  }
  cell(0.6, 8.0, 5.2, 1.2, [left side meets right], fill: luma(205))
  cell(6.4, 8.0, 7.4, 1.2, [int32 array], fill: luma(205))
  cell(14.2, 8.0, 7.2, 1.2, [float32 array], fill: luma(205))
  cell(0.6, 6.4, 5.2, 1.3, [python int 1])
  cell(6.4, 6.4, 7.4, 1.3, [int32, weak adopts])
  cell(14.2, 6.4, 7.2, 1.3, [float32, cross kind to f64])
  cell(0.6, 4.8, 5.2, 1.3, [python float 1.5])
  cell(6.4, 4.8, 7.4, 1.3, [float64, cross kind])
  cell(14.2, 4.8, 7.2, 1.3, [float32, weak adopts])
  cell(0.6, 3.2, 5.2, 1.3, [np.int64 scalar])
  cell(6.4, 3.2, 7.4, 1.3, [int64, strong wins])
  cell(14.2, 3.2, 7.2, 1.3, [float64, kind wins])
  cell(0.6, 1.6, 5.2, 1.3, [256 into int8], fill: luma(245))
  cell(6.4, 1.6, 15.0, 1.3, [OverflowError, python integer #linebreak() out of bounds, never a wrap], fill: luma(245))
  cdraw.content((11.0, 0.5), [in place keeps its dtype or refuses under same_kind, uint64 plus int64 lands in float64], wrap: text.with(size: 6.5pt, fill: luma(100)))
})

#callout("verify", "38 checks, the pin asserted first", [
  A scoped run, `pwsh tools/run-py-samples.ps1 -Chapter Ch24`, walks the
  four samples through the run and format legs and reports: 4 files, 38
  checks, format clean. `ndarray.py` carries the interpreter and numpy
  pins and contributes 9, the stride triple, both stride orders, the
  constructors, and the view and copy split with its mutation proof.
  `broadcast.py` adds 13, the loop equivalence, the (4, 3) broadcast, the
  quoted mismatch message, the read-only stretch, the axis family, and
  the reduction dtypes. `masks.py` adds 9, masks and integer arrays, the
  two roles of `where`, the scatter trap against `add.at`, and the nan
  aware ufuncs. `dtypes.py` adds 7, the weak and strong columns, three
  exact overflow messages, the in place rule, both string dtypes, and
  the datetime facts. Every expected value was produced by this venv,
  then pinned.
])

sources: numpy.org/doc/2.5/reference/arrays.ndarray.html (the memory
layout attribute definitions, shape, strides, itemsize, base),
numpy.org/doc/2.5/user/basics.indexing.html (basic slicing always views,
advanced indexing always copies), numpy.org/doc/2.5/user/basics.broadcasting.html
(element-wise shape comparison, the two compatibility conditions, the
ValueError wording, looping in C), numpy.org/neps/nep-0050-promotion_rules.html
(weakly typed python scalars, values never influence result type, the
error on conversion), numpy.org/doc/2.5/reference/arrays.datetime.html
(date and time unit strings, the busday functions), all accessed
2026-09-12. Overflow message texts, the uint8 wrap to 4, the chained
base behavior, and every expected value probed on this machine under the
pinned venv the same day. Sample behavior verified by `make verify-py`,
38 checks in chapter 24.
