// book 5 manifest: chapter registry used by cross references and stubs
#let csharpnet = (
  num: 5,
  volume: false,
  title: "c# 15, f# 11, and .net 11",
  meta: (
    title: "c# 15, f# 11, and .net 11",
    subtitle: "a complete c# manual with an f# tour",
    author: "gabriel la",
    version: "5.0",
    volume-label: "book 5",
  ),
  chapters: (
    (id: "toolchain", num: 1, title: "toolchain and project model"),
    (id: "lexical", num: 2, title: "lexical structure"),
    (id: "typesystem", num: 3, title: "the type system"),
    (id: "members", num: 4, title: "members"),
    (id: "generics", num: 5, title: "generics"),
    (id: "patterns", num: 6, title: "pattern matching and control flow"),
    (id: "delegates", num: 7, title: "delegates, lambdas, events"),
    (id: "exceptions", num: 8, title: "exceptions"),
    (id: "async", num: 9, title: "async"),
    (id: "memory", num: 10, title: "memory and runtime"),
    (id: "allocation", num: 11, title: "allocation: the managed heap, pools, and arenas"),
    (id: "profilers", num: 12, title: "profilers: benchmarkdotnet, counters, and p99"),
    (id: "reflection", num: 13, title: "reflection, attributes, source generators"),
    (id: "linq", num: 14, title: "linq"),
    (id: "stdlib1", num: 15, title: "stdlib tour 1: collections, memory, numerics"),
    (id: "stdlib2", num: 16, title: "stdlib tour 2: io, text, net, channels, diagnostics"),
    (id: "idioms", num: 17, title: "idioms"),
    (id: "functional", num: 18, title: "functional programming"),
    (id: "fsharp-language", num: 19, title: "f# 11: values, functions, and types"),
    (id: "fsharp-pipeline", num: 20, title: "f# 11: collections, pipelines, and async"),
    (id: "fsharp-dotnet", num: 21, title: "f# on .net 11"),
    (id: "api-kernel", num: 22, title: "api kernel"),
    (id: "middleware", num: 23, title: "middleware"),
    (id: "users", num: 24, title: "the user resource"),
    (id: "authn", num: 25, title: "authn"),
    (id: "authz", num: 26, title: "authz and rbac"),
    (id: "store", num: 27, title: "store"),
    (id: "conc", num: 28, title: "concurrency control"),
    (id: "cache", num: 29, title: "caching"),
    (id: "limit", num: 30, title: "rate limiting"),
    (id: "obs", num: 31, title: "observability"),
    (id: "load", num: 32, title: "load and p99"),
    (id: "shipit", num: 33, title: "ship it"),
    (id: "suite", num: 34, title: "the test suite"),
    (id: "capstone", num: 35, title: "capstone: a small language interpreter"),
    (id: "appendices", num: 36, title: "appendices: coverage and sources"),
  ),
)
