#import "../../theme/lib.typ": listing, snippet, callout, diagram, cdraw, xref-to

= groups and subgroups

A group is a set with one operation that never leaves you stranded: every product stays inside, the identity is there, and every element can be undone. This chapter treats those axioms the way this book treats everything, as executable claims: closure, associativity, identity, and inverses become scan loops over fixed tables, first on $Z_6$ addition, the units mod 8, and integer matrices with determinant $plus.minus 1$, then on the residue classes $Z_n$ and their multiplicative units $U(n)$ where order and $phi$ meet, then subgroups generated by a single element with the divisor-shaped lattice of $Z_12$, then cyclic groups and which elements generate them, then cosets and the theorem of Lagrange that an order must divide an order, and finally the two non-abelian families this book actually uses, the six symmetries of a triangle ($S_3$) and the matrix group $"SL"_2(Z)$. Every behavioral claim below is one of the 58 checks in the 4 samples of chapter 16 or a sentence quoted from a canonical source fetched 2026-09-21. Where #xref-to("dsa", "numtheory") runs modular exponentiation and primality as algorithms, this chapter is the theory underneath: why those residue sets are groups at all and what divides what.

== the axioms as a check suite

Definition first. A group is a pair $(G, dot)$ of a set and a binary operation such that all four axioms hold: closure, $a dot b in G$ for all $a, b in G$, associativity, $(a dot b) dot c = a dot (b dot c)$, an identity $e$ with $e dot a = a dot e = a$, and an inverse $a^(-1)$ with $a dot a^(-1) = e$, for every $a$. The group is abelian when moreover $a dot b = b dot a$. These are definition 2.7 of the mml-book draft 2024-01-15, sec 2.4.1 [printed pp 36-37 / pdf pp 42-43], whose example 2.10 runs the same recognition game, $(Z, +)$ a group while $(N_0, +)$ and $(Z, dot)$ both lose exactly on inverses. The four axioms are exactly four loop nests, which is why they make a good first sample: nothing about a group needs floating point, every question is a scan over a finite table or an exact integer identity.

The three fixtures of this section: $Z_6$, the residues $0..5$ under addition mod 6, identity 0, inverse of $k$ is $(6 - k) mod 6$, so the pinned inverse pairs are $(1,5)$, $(2,4)$, $(3,3)$. The units mod 8, $U(8) = {1, 3, 5, 7}$ under multiplication mod 8, where every element is its own inverse, $3 dot 3 = 9 = 1$, and the pinned row of the table through 3 is ${3, 1, 7, 5}$ because $3 dot 5 = 15 = 7$ and $3 dot 7 = 21 = 5$ mod 8. And two matrices from $"SL"_2 (Z)$, the 2 by 2 integer matrices of determinant 1: the quarter turn $S = mat(0, -1, 1, 0)$ and the shear $T = mat(1, 1, 0, 1)$.

The dry run: the matrix pair shows why the determinant condition is the right one, and then the same table machinery kills three near-miss structures.

+ Determinants multiply: $det(S) = 0 dot 0 - (-1) dot 1 = 1$ and $det(T) = 1$, so $det(S T) = 1 dot 1 = 1$, closure on the nose.
+ But the product is not symmetric: $S T = mat(0, -1, 1, 1)$ while $T S = mat(1, -1, 1, 0)$, two different integer matrices, so this family is already non-abelian.
+ Inverses come from the adjugate: $S^(-1) = mat(0, 1, -1, 0)$ and $T^(-1) = mat(1, -1, 0, 1)$, both integer matrices because $det = plus.minus 1$ means dividing by the determinant divides by 1.

#listing("math/samples/src/Ch16/axioms.c", first: 141, last: 172, caption: [axioms.c, the sl2(z) entry: determinants multiply, the product order matters, and adjugate gives integer inverses exactly when det is plus or minus 1])

The near-miss table is the other half of the definition. A structure can pass three axioms and die on the fourth, and each failure mode below is a check:

#table(
  columns: (auto, auto, auto, auto, auto),
  inset: 4pt,
  table.header([*structure*], [*closure*], [*assoc*], [*identity*], [*inverses*]),
  [$Z_6$, add], [yes], [yes], [0], [yes],
  [$U(8)$, mult], [yes], [yes], [1], [yes],
  [det $plus.minus 1$ matrices], [yes], [yes], [$I$], [yes],
  [$Z ∖ {0}$, mult], [yes], [yes], [1], [no],
  [$Z$, subtract], [yes], [no], [no], [n/a],
  [all of $Z_10$, mult], [yes], [yes], [1], [no],
)

#listing("math/samples/src/Ch16/axioms.c", first: 174, last: 195, caption: [axioms.c, the three near-misses: subtraction breaks associativity at (1-2)-3 = -4 versus 2, and 2 has no multiplicative inverse over the integers or mod 10])

#callout("pitfall", "associativity is the axiom you cannot eyeball", [
  every structure above looks plausible, and the one that fails hardest is the one people reach for first: subtraction. the pin is one line, $(1 - 2) - 3 = -4$ while $1 - (2 - 3) = 2$, but exponentiation by repeated squaring, composition chains, and fold order all inherit this axiom silently. when you define an operation in code, scan all triples before you build on it, checks 1 and 5 of axioms.c do exactly that on 216 and 64 triples.
])

#diagram([the axiom gates: four checks in sequence, three near-miss structures dropping out where they fail], length: 13pt, {
  let gate(x, y, w, t) = {
    cdraw.rect((x, y), (x + w, y + 0.9), fill: luma(235), radius: 0.02, stroke: luma(100))
    cdraw.content((x + w / 2, y + 0.45), t, size: 6pt)
  }
  gate(6.4, 6.6, 4.0, [closure])
  gate(6.4, 5.2, 4.0, [associativity])
  gate(6.4, 3.8, 4.0, [identity])
  gate(6.4, 2.4, 4.0, [inverses])
  cdraw.line((8.4, 6.6), (8.4, 6.1), stroke: luma(60), mark: (end: ">"))
  cdraw.line((8.4, 5.2), (8.4, 4.7), stroke: luma(60), mark: (end: ">"))
  cdraw.line((8.4, 3.8), (8.4, 3.3), stroke: luma(60), mark: (end: ">"))
  cdraw.rect((6.4, 1.0), (10.4, 1.9), fill: luma(205), radius: 0.02, stroke: luma(60))
  cdraw.content((8.4, 1.45), [group], size: 6.5pt)
  cdraw.line((8.4, 2.4), (8.4, 1.9), stroke: luma(60), mark: (end: ">"))
  let miss(x, y, w, t) = {
    cdraw.rect((x, y), (x + w, y + 0.9), fill: luma(245), radius: 0.02, stroke: (paint: luma(150), dash: "dashed"))
    cdraw.content((x + w / 2, y + 0.45), t, size: 6pt)
  }
  miss(0.3, 5.2, 4.4, [Z under subtraction])
  miss(0.3, 2.4, 4.4, [nonzero Z, times])
  miss(0.3, 0.6, 4.4, [$Z_10$, all residues, times])
  cdraw.line((4.7, 5.65), (6.4, 5.65), stroke: (paint: luma(140), dash: "dashed"))
  cdraw.content((4.9, 5.95), [assoc fails], size: 6pt)
  cdraw.line((4.7, 2.85), (6.4, 2.85), stroke: (paint: luma(140), dash: "dashed"))
  cdraw.content((4.9, 3.5), [no inverse for 2], size: 6pt)
  cdraw.line((4.7, 1.05), (5.6, 1.05), stroke: (paint: luma(140), dash: "dashed"))
  cdraw.line((5.6, 1.05), (5.6, 2.65), stroke: (paint: luma(140), dash: "dashed"))
  cdraw.line((5.6, 2.65), (6.4, 2.65), stroke: (paint: luma(140), dash: "dashed"))
  cdraw.content((3.4, 1.95), [2x != 1], size: 6pt)
})

== z mod n and its units

The residue classes $Z_n$ carry two operations at once. Under addition mod $n$, $Z_n$ is a group immediately: closure is reduction, associativity inherits from the integers, the identity is 0, and $n - k$ inverts $k$. Under multiplication mod $n$, all residues form only a monoid, a group minus inverses: $2 x equiv 1 mod 10$ has no solution because $gcd(2, 10) = 2$ divides any multiple of 2, so 2 never lands on 1. Deleting the zero divisors repairs it: the units $U(n) = {k : gcd(k, n) = 1}$ are exactly the invertible residues, a group under multiplication mod $n$, and its order is the totient, $|U(n)| = phi(n)$ (Wikipedia, "multiplicative group of integers modulo n", fetched 2026-09-21: "an abelian, finite group whose order is given by Euler's totient function").

The pinned totals for this chapter's fixtures: $phi(5) = 4$, $phi(8) = 4$, $phi(9) = 6$, $phi(10) = 4$, $phi(12) = 4$, each confirmed by a coprime scan that also counts $|U(n)|$, checks 8 and 9 of units.c.

The dry run: inside $U(10) = {1, 3, 7, 9}$, take powers of 3.

+ $3^1 = 3$, then $3^2 = 9$, then $3^3 = 27 = 7$ mod 10, then $3^4 = 21 = 1$ mod 10: the ladder is 3, 9, 7, 1 and the order of 3 is 4.
+ Powers of 9 die faster: $9^2 = 81 = 1$ mod 10, ladder 9, 1, order 2.
+ Every order divides the group order 4: the pinned orders are 1, 4, 4, 2 for the elements 1, 3, 7, 9, and $1 divides 4$, $2 divides 4$, $4 divides 4$. That divisibility is Lagrange knocking, five sections early.

#table(
  columns: (auto, auto, auto, auto),
  inset: 4pt,
  table.header([*element of u(10)*], [*ladder*], [*order*], [*divides 4*]),
  [1], [1], [1], [yes],
  [3], [3, 9, 7, 1], [4], [yes],
  [7], [7, 9, 3, 1], [4], [yes],
  [9], [9, 1], [2], [yes],
)

#listing("math/samples/src/Ch16/units.c", first: 122, last: 148, caption: [units.c, the ladders of 3 and 9 mod 10 pinned step by step, with every order checked against divisibility by 4])

The order observations generalize to the two classic theorems, both of them one-line corollaries of the group structure once Lagrange lands. Euler: for any unit $a$ mod $n$, $a^(phi(n)) equiv 1 mod n$, pinned here as $3^4 = 81 equiv 1 mod 10$ and $5^4 = 625 equiv 1 mod 12$. Fermat: for prime $p$ and $a != 0$, $a^(p - 1) equiv 1 mod p$, since $U(p)$ is all of ${1, ..., p - 1}$ and $phi(p) = p - 1$. The prime fixture is $3^100 equiv 1 mod 101$, sharpened to the exact statement that 3 generates all of $U(101)$: its order is 100, with $3^50 = 100 equiv -1 mod 101$ sitting at the halfway point.

#listing("math/samples/src/Ch16/units.c", first: 173, last: 188, caption: [units.c, euler and fermat pins: two small ladders and the primitive root 3 mod 101 with order exactly 100])

#callout("verify", "the algorithm lives in the dsa book", [
  the samples pin powers with a 12-line square-and-multiply loop over uint64, widths stated in the file (moduli capped at 101 so squares fit). that loop as an algorithm, with its role in fast exponentiation, primality testing, and RSA-style arithmetic, is chapter material of #xref-to("dsa", "numtheory") and #xref-to("dsa", "numtheory2"). this chapter only needs its outputs: exact orders, exact divisibility.
])

#diagram([the power cycles of u(10): multiplying by 3 walks a 4-cycle, the sub-ladder of 9 collapses to a 2-cycle], length: 13pt, {
  let node(x, y, t, dark) = {
    cdraw.rect((x - 0.5, y - 0.45), (x + 0.5, y + 0.45), fill: if dark { luma(205) } else { luma(245) }, radius: 0.02, stroke: luma(100))
    cdraw.content((x, y), t, size: 6.5pt)
  }
  node(1.6, 5.2, [1], false)
  node(5.2, 5.2, [3], true)
  node(5.2, 1.8, [9], false)
  node(1.6, 1.8, [7], false)
  cdraw.line((2.1, 5.2), (4.7, 5.2), stroke: luma(60), mark: (end: ">"))
  cdraw.content((3.4, 5.45), [x3], size: 6pt)
  cdraw.line((5.2, 4.75), (5.2, 2.25), stroke: luma(60), mark: (end: ">"))
  cdraw.content((5.45, 3.5), [x3], size: 6pt)
  cdraw.line((4.7, 1.8), (2.1, 1.8), stroke: luma(60), mark: (end: ">"))
  cdraw.content((3.4, 2.05), [x3], size: 6pt)
  cdraw.line((1.6, 2.25), (1.6, 4.75), stroke: luma(60), mark: (end: ">"))
  cdraw.content((1.85, 3.5), [x3], size: 6pt)
  cdraw.line((2.1, 4.75), (4.7, 2.25), stroke: (paint: luma(150), dash: "dashed"), mark: (end: ">"))
  cdraw.line((4.7, 2.25), (2.1, 4.75), stroke: (paint: luma(150), dash: "dashed"), mark: (end: ">"))
  cdraw.content((8.6, 3.5), [dashed: x9 twice, order 2], size: 6pt)
  cdraw.content((3.4, 0.6), [solid ring: order of 3 is 4 = |u(10)|], size: 6pt)
})

== subgroups and the subgroup one element generates

A subgroup $H$ of $G$ is a subset that is a group under the same operation: it must contain $e$, and be closed under products and inverses. For a finite set inside a group the test collapses to nonempty plus closure under products, because repeated products cycle and pull the identity and inverses out on their own. The cheapest source of subgroups is a single element: $⟨g⟩ = {g, g^2, g^3, ...}$, the cyclic subgroup generated by $g$, is closed by construction, and the order of $g$, written $"ord"(g)$, is defined as $|⟨g⟩|$, the first exponent that returns to $e$ (Wikipedia, "cyclic group", fetched 2026-09-21: the order of an element "is equal to the order of the cyclic subgroup that it generates").

$Z_12$ is the fixture because its subgroups are exactly one per divisor. The dry run: repeated addition of a single element, the subgroup it generates pinned run by run:

+ $⟨4⟩ = {0, 4, 8}$: three steps back to 0, order 3.
+ $⟨3⟩ = {0, 3, 6, 9}$: four steps, order 4.
+ $⟨2⟩ = {0, 2, 4, 6, 8, 10}$: six steps, order 6.
+ $⟨1⟩$ is all of $Z_12$, order 12, and the full pinned size row for $k = 0..11$ is 1, 12, 6, 4, 3, 12, 2, 12, 3, 4, 6, 12, which is $12 slash gcd(12, k)$ entry by entry.

#table(
  columns: (auto, auto, auto, auto),
  inset: 4pt,
  table.header([*k in z12*], [*⟨k⟩*], [*$|⟨k⟩|$*], [*$12 slash gcd(12,k)$*]),
  [0], [{0}], [1], [1],
  [1], [all 12], [12], [12],
  [2], [{0,2,4,6,8,10}], [6], [6],
  [3], [{0,3,6,9}], [4], [4],
  [4], [{0,4,8}], [3], [3],
  [6], [{0,6}], [2], [2],
)

#listing("math/samples/src/Ch16/cyclic.c", first: 76, last: 101, caption: [cyclic.c, the pinned subgroup masks of z12 as bit patterns, then the generator scan: exactly the coprime residues 1, 5, 7, 11 cover the whole group])

Two structural facts fall out of the same scan, both CHECKed. First, the 12 runs $⟨k⟩$ collapse to exactly 6 distinct subsets, one subgroup per divisor $d in {1, 2, 3, 4, 6, 12}$, and the subgroup of order $d$ is $⟨12 slash d⟩$: $|⟨12 slash d⟩| = d$ pinned on all six divisors. Second, every subgroup of a cyclic group is cyclic, visibly here: each of the 6 is one of the runs. The lattice picture is worth holding onto, it reappears as the divisor order of #xref-to("math", "graphs") dressed as a Hasse diagram, and the same divisibility shape governs which subgroups exist in every cyclic group you will meet in #xref-to("math", "actions").

#diagram([the subgroup lattice of z12, one subgroup per divisor of 12, edges are containment], length: 13pt, {
  let node(x, y, t, dark) = {
    cdraw.rect((x - 1.3, y - 0.45), (x + 1.3, y + 0.45), fill: if dark { luma(205) } else { luma(235) }, radius: 0.02, stroke: luma(100))
    cdraw.content((x, y), t, size: 6pt)
  }
  node(8.0, 6.4, [⟨1⟩, order 12], true)
  node(5.0, 4.9, [⟨2⟩, order 6], false)
  node(11.0, 4.9, [⟨3⟩, order 4], false)
  node(5.2, 3.4, [⟨4⟩, order 3], false)
  node(9.0, 3.4, [⟨6⟩, order 2], false)
  node(7.0, 1.9, [⟨0⟩, order 1], false)
  cdraw.line((7.6, 5.95), (5.4, 5.35), stroke: luma(60))
  cdraw.line((8.4, 5.95), (10.6, 5.35), stroke: luma(60))
  cdraw.line((4.8, 4.45), (5.15, 3.85), stroke: luma(60))
  cdraw.line((5.2, 4.45), (8.8, 3.85), stroke: luma(60))
  cdraw.line((11.0, 4.45), (9.2, 3.85), stroke: luma(60))
  cdraw.line((5.6, 2.95), (6.7, 2.35), stroke: luma(60))
  cdraw.line((8.6, 2.95), (7.3, 2.35), stroke: luma(60))
  cdraw.content((2.6, 0.9), [every subgroup here is cyclic], size: 6pt)
  cdraw.content((2.6, 0.3), [one per divisor of 12], size: 6pt)
})

== cyclic groups and generator search

A group is cyclic when one element reaches everything: $G = ⟨g⟩$ for some generator $g$. Every cyclic group of order $n$ is a copy of $Z_n$ (Wikipedia, "cyclic group": "every finite cyclic group of order n is isomorphic to the additive group of Z/nZ"), so generator search is a question about residues, and it has a complete answer: a modular integer $k$ generates $Z_n$ exactly when $gcd(k, n) = 1$, and the number of generators is $phi(n)$. In $Z_12$ the scan above found 1, 5, 7, 11, four of them, and $phi(12) = 4$.

The multiplicative side is where it gets interesting, because $U(n)$ may or may not be cyclic. The classification is classical, first proved by Gauss: $U(n)$ is cyclic exactly for $n = 1, 2, 4, p^k, 2 p^k$ with $p$ an odd prime (Wikipedia, "multiplicative group of integers modulo n", fetched 2026-09-21). The dry run: the fixtures walk both sides of the classification:

+ $U(5)$, order 4, cyclic: the ladder of 2 is 2, 4, 3, 1, all four units.
+ $U(7)$, order 6, cyclic: the ladder of 3 is 3, 2, 6, 4, 5, 1, all six units, prime modulus so $|U(p)| = p - 1$.
+ $U(9)$, order $phi(9) = 6$, cyclic: the ladder of 2 is 2, 4, 8, 7, 5, 1, a prime power.
+ $U(8)$ and $U(12)$, order 4 each, not cyclic: every nonidentity element squares to 1, the pinned Klein pattern, so no ladder can visit all 4.

The order rule that makes ladders predictable, again from the cyclic group page: the order of an element $m$ in $Z_n$ is $n slash gcd(n, m)$, and in any cyclic group of order $n$ with generator $g$, $"ord"(g^k) = n slash gcd(n, k)$. In $U(7)$ with $g = 3$, $n = 6$: $3^2 = 2$ has order $6 slash gcd(6, 2) = 3$, pinned ladder 2, 4, 1, and $3^3 = 6$ has order $6 slash gcd(6, 3) = 2$, ladder 6, 1.

#table(
  columns: (auto, auto, auto, auto),
  inset: 4pt,
  table.header([*$3^k$ in u(7)*], [*element*], [*$"ord"$*], [*$6 slash gcd(6,k)$*]),
  [$k = 1$], [3], [6], [6],
  [$k = 2$], [2], [3], [3],
  [$k = 3$], [6], [2], [2],
  [$k = 4$], [4], [3], [3],
  [$k = 5$], [5], [6], [6],
  [$k = 6$], [1], [1], [1],
)

#listing("math/samples/src/Ch16/cyclic.c", first: 159, last: 201, caption: [cyclic.c, u(7) cyclic with the ladder of 3, the order rule ord(g^k) = n/gcd(n,k) verified per power, then the klein contrasts u(12) and the prime power u(9)])

#callout("pitfall", "same order, different group", [
  $|U(5)| = |U(8)| = |U(12)| = 4$, yet u(5) is a 4-cycle and u(8), u(12) are klein groups where everything squares to 1. group order alone does not determine the group, which is why the samples pin ladders, not just counts. the same warning runs forward: two-element subgroups are all alike, but the two groups of order 4 are genuinely different machines, and burnside counting in #xref-to("math", "actions") will care which one it is looking at.
])

#diagram([the z12 residue wheel, the four coprime residues shaded as the generators, count phi(12) = 4], length: 13pt, {
  // cos/sin at multiples of 30 degrees, radius 2.8, center (5.5, 3.6)
  let xs = (2.8, 2.42, 1.4, 0.0, -1.4, -2.42, -2.8, -2.42, -1.4, 0.0, 1.4, 2.42)
  let ys = (0.0, 1.4, 2.42, 2.8, 2.42, 1.4, 0.0, -1.4, -2.42, -2.8, -2.42, -1.4)
  let cell(k, dark) = {
    let x = 5.5 + xs.at(k)
    let y = 3.6 + ys.at(k)
    cdraw.rect((x - 0.38, y - 0.38), (x + 0.38, y + 0.38), fill: if dark { luma(205) } else { luma(245) }, radius: 0.02, stroke: luma(100))
    cdraw.content((x, y), str(k), size: 6pt)
  }
  for k in range(12) {
    cell(k, k in (1, 5, 7, 11))
  }
  cdraw.content((5.5, 3.6), [step +1], size: 6pt)
  cdraw.content((13.0, 3.6), [generators: gcd(k,12) = 1], size: 6pt)
  cdraw.content((13.0, 3.0), [1, 5, 7, 11, count phi(12) = 4], size: 6pt)
})

== order, cosets, and lagrange

The theorem this chapter exists for. For a subgroup $H$ of a finite group $G$, the left cosets are the translates $g H = {g dot h : h in H}$, and Lagrange's theorem states the partition arithmetic: $|G| = [G : H] dot |H|$, where $[G : H]$ is the number of distinct cosets (Wikipedia, "Lagrange's theorem (group theory)", fetched 2026-09-21: "if H is a subgroup of any finite group G, then |H| is a divisor of |G|. That is, the order (number of elements) of every subgroup divides the order of the whole group"). The proof is three short steps and worth doing, because it is the model for every counting argument in #xref-to("math", "actions").

+ Every coset has size exactly $|H|$: the map $h arrow.r g dot h$ is a bijection $H -> g H$, with inverse $g h arrow.r h$ computed by multiplying on the left by $g^(-1)$.
+ Distinct cosets are disjoint: if $g_1 H ∩ g_2 H$ is nonempty, pick $g_1 h_1 = g_2 h_2$, then $g_1 = g_2 h_2 h_1^(-1)$ forces $g_1 H = g_2 H$. So the cosets "form a partition of G", equal-size classes of the equivalence relation $x ~ y$ iff $x = y h$ for some $h in H$.
+ Count the partition: $|G|$ elements split into $[G : H]$ classes of $|H|$ each, so $|G| = [G : H] dot |H|$ and $|H|$ divides $|G|$.

The dry run: the additive cosets of $⟨3⟩ = {0, 3, 6, 9}$ inside $Z_12$, translation instead of multiplication because the group is additive.

+ $0 + ⟨3⟩ = {0, 3, 6, 9}$, the subgroup itself.
+ $1 + ⟨3⟩ = {1, 4, 7, 10}$ and $2 + ⟨3⟩ = {2, 5, 8, 11}$, two fresh sets.
+ $3 + ⟨3⟩$ lands back on the first coset, so the run stops: exactly 3 cosets of size 4, tiling all 12 residues with no overlap, $12 = 3 dot 4$.

#table(
  columns: (auto, auto, auto),
  inset: 4pt,
  table.header([*coset of ⟨3⟩ in z12*], [*members*], [*size*]),
  [$0 + ⟨3⟩$], [{0, 3, 6, 9}], [4],
  [$1 + ⟨3⟩$], [{1, 4, 7, 10}], [4],
  [$2 + ⟨3⟩$], [{2, 5, 8, 11}], [4],
)

#listing("math/samples/src/Ch16/cosets.c", first: 267, last: 281, caption: [cosets.c, the z12 coset construction from the subgroup bitmask, pinned as 0x249, 0x492, 0x924, and checked to tile the 12 residues exactly])

The corollary with teeth: since $⟨g⟩$ is a subgroup for every element, $"ord"(g) = |⟨g⟩|$ divides $|G|$, and consequently $g^(|G|) = e$ for every element of a finite group (the Lagrange page again: "If the group has n elements, it follows $a^n = e$"). Euler and Fermat from the second section are this corollary in disguise: $U(n)$ has $phi(n)$ elements, so every unit satisfies $a^(phi(n)) = 1$, and prime moduli give $a^(p - 1) = 1$. Gauss proved exactly that case, the multiplicative group mod a prime, in the Disquisitiones Arithmeticae of 1801, decades before the general theorem.

#listing("math/samples/src/Ch16/cosets.c", first: 283, last: 313, caption: [cosets.c, the lagrange fixtures: every subgroup order in z12 divides 12, every element order in u(10) divides 4, and both coset identities hold, 6 = 3 x 2 and 12 = 3 x 4])

#callout("note", "the converse is false", [
  lagrange says every subgroup order divides the group order, not that every divisor is a subgroup order. the standard witness is $A_4$, the 12 even permutations of four labels: it has no subgroup of order 6, though $6 divides 12$. the samples never test the converse, they only test the divisibility direction that the theorem guarantees.
])

#diagram([the coset tiling of z12 by ⟨3⟩: three disjoint translates of size 4 covering all 12 residues], length: 13pt, {
  let cell(x, y, t, fill) = {
    cdraw.rect((x, y), (x + 1.5, y + 0.9), fill: fill, radius: 0.02, stroke: luma(100))
    cdraw.content((x + 0.75, y + 0.45), t, size: 6.5pt)
  }
  cdraw.content((-1.6, 5.75), [2 + ⟨3⟩], size: 6pt)
  cdraw.content((-1.6, 4.45), [1 + ⟨3⟩], size: 6pt)
  cdraw.content((-1.6, 3.15), [⟨3⟩], size: 6pt)
  cell(0.3, 5.3, [2], luma(245))
  cell(1.9, 5.3, [5], luma(245))
  cell(3.5, 5.3, [8], luma(245))
  cell(5.1, 5.3, [11], luma(245))
  cell(0.3, 4.0, [1], luma(235))
  cell(1.9, 4.0, [4], luma(235))
  cell(3.5, 4.0, [7], luma(235))
  cell(5.1, 4.0, [10], luma(235))
  cell(0.3, 2.7, [0], luma(205))
  cell(1.9, 2.7, [3], luma(205))
  cell(3.5, 2.7, [6], luma(205))
  cell(5.1, 2.7, [9], luma(205))
  cdraw.rect((0.05, 5.05), (6.85, 6.45), stroke: (paint: luma(140), dash: "dashed"))
  cdraw.rect((0.05, 3.75), (6.85, 5.15), stroke: (paint: luma(140), dash: "dashed"))
  cdraw.rect((0.05, 2.45), (6.85, 3.85), stroke: (paint: luma(140), dash: "dashed"))
  cdraw.content((3.4, 1.7), [3 cosets x 4 elements = 12 = |G|], size: 6pt)
  cdraw.content((3.4, 1.1), [index: 3 cosets], size: 6pt)
})

== permutations, matrices, and the triangle

The two families that make the abstraction pay. Permutations of $n$ labels form the symmetric group $S_n$ under function composition, order $n!$, and at $n = 3$ it is small enough to table and big enough to be non-abelian: $D_3$, the six symmetries of an equilateral triangle, "is isomorphic to the symmetric group S3" and "is also the smallest non-abelian group" (Wikipedia, "dihedral group of order 6", fetched 2026-09-21). The samples encode a permutation as the triple of images $(p(0), p(1), p(2))$, compose as $a ∘ b$ meaning apply $b$ first, $(a ∘ b)(x) = a[b[x]]$, and check the whole package on the six elements $e$, $r = (0 1 2)$, $r^2 = (0 2 1)$, and the three swaps $"s01", "s02", "s12"$.

The dry run: two compositions that refuse to commute, plus the order of each element.

+ $"s01" ∘ r$ applies the rotation then the swap: $r$ sends $0 -> 1$, $1 -> 2$, $2 -> 0$, and the swap exchanges 0 and 1, so the composite fixes 0 and exchanges 1 and 2, giving $(0, 2, 1) = "s12"$.
+ $r ∘ "s01"$ swaps first, then rotates: $0$ goes $0 -> 1 -> 2$, $1$ goes $1 -> 0 -> 1$, $2$ goes $2 -> 2 -> 0$, giving $(2, 1, 0) = "s02"$, a different element, so the group is non-abelian.
+ Orders: $"ord"(e) = 1$, $"ord"(r) = "ord"(r^2) = 3$, every swap has order 2, and each of 1, 2, 3 divides $|S_3| = 6$, Lagrange verified element by element.

#listing("math/samples/src/Ch16/cosets.c", first: 40, last: 64, caption: [cosets.c, the permutation representation: composition as a after b over image triples, and element order as repeated composition back to the identity])

The coset machinery from the last section now runs on a non-abelian group, and the partitions it finds are the two splittings of $S_3$ worth remembering. For $H = {e, "s01"}$: the three left cosets are ${e, "s01"}$, ${r, "s02"}$, and ${"s12", r^2}$, each of size 2, tiling the 6 elements exactly, $6 = 3 dot 2$. For the rotation subgroup $⟨r⟩ = {e, r, r^2}$: exactly 2 cosets of size 3, and the second one is all three reflections at once, rotations versus flips, $6 = 2 dot 3$. The same sample file closes with the trap that gives Lagrange its fine print: $"SL"_2 (Z)$, the determinant-1 integer matrices, is an infinite group, the integer echo of the general linear group of mml definition 2.8 [printed p 37 / pdf p 43], and inside it the quarter turn $S = mat(0, -1, 1, 0)$ satisfies $S^2 = -I$, $S^4 = I$, so $"ord"(S) = 4$ while no finite $|G|$ exists to divide. Finiteness is a hypothesis of the theorem, not a decoration.

#listing("math/samples/src/Ch16/cosets.c", first: 193, last: 220, caption: [cosets.c, the left coset construction on s3: translate the subgroup by every element, deduplicate, and land on exactly 3 distinct cosets])

#listing("math/samples/src/Ch16/cosets.c", first: 315, last: 328, caption: [cosets.c, the infinity trap: the quarter turn has order 4 inside the infinite group sl2(z), where lagrange has nothing to say])

#table(
  columns: (auto, auto, auto, auto),
  inset: 4pt,
  table.header([*s3 element*], [*triple*], [*order*], [*inverse*]),
  [e], [(0,1,2)], [1], [e],
  [r], [(1,2,0)], [3], [$r^2$],
  [$r^2$], [(2,0,1)], [3], [r],
  [$"s01"$], [(1,0,2)], [2], [$"s01"$],
  [$"s02"$], [(2,1,0)], [2], [$"s02"$],
  [$"s12"$], [(0,2,1)], [2], [$"s12"$],
)

#diagram([the labeled triangle: the rotation r cycles all three vertex labels, the reflection s fixes vertex 2 and swaps 0 with 1, together generating all six symmetries], length: 13pt, {
  let v0 = (1.2, 0.8)
  let v1 = (5.2, 0.8)
  let v2 = (3.2, 4.264) // equilateral: height 2*sqrt(3) = 3.464 on base 4.0
  cdraw.line(v0, v1, stroke: luma(100), mark: (end: ">"))
  cdraw.line(v1, v2, stroke: luma(100), mark: (end: ">"))
  cdraw.line(v2, v0, stroke: luma(100), mark: (end: ">"))
  let dot(p, t) = {
    cdraw.circle(p, radius: 0.42, fill: luma(205), stroke: luma(60))
    cdraw.content(p, t, size: 6.5pt)
  }
  dot(v0, [0])
  dot(v1, [1])
  dot(v2, [2])
  cdraw.line((3.2, 4.264), (3.2, 0.8), stroke: (paint: luma(150), dash: "dashed"))
  cdraw.content((3.2, 0.15), [r = (0 1 2)], size: 6pt)
  cdraw.content((4.9, 3.1), [s = (0 1)], size: 6pt)
  cdraw.content((8.8, 3.0), [r: order 3, fixes nothing], size: 6pt)
  cdraw.content((8.8, 2.4), [s: order 2, fixes vertex 2], size: 6pt)
  cdraw.content((8.8, 1.8), [r and s generate all 6], size: 6pt)
})

The vocabulary lands where it was headed: group, order, subgroup, cyclic generator, and cosets partitioning a group are exactly the nouns #xref-to("math", "actions") picks up to make a group act on a set, count orbits with Burnside, and build the finite fields the later chapters compute over.

sources: mml-book draft 2024-01-15, sec 2.4.1 groups, definition 2.7 the four axioms with the abelian addendum and example 2.10 groups and non-groups [printed pp 36-37 / pdf pp 42-43], plus definition 2.8 the general linear group [printed p 37 / pdf p 43], anchoring the section 1 definitions and the section 6 matrix family. The coset, cyclic, and permutation structure sections carry no mml anchors and were authored from canonical texts by name and four fetched pages. Dummit and Foote, Abstract Algebra, 3rd ed 2004, ch 1 the axioms and first examples, ch 2 subgroups and cyclic groups, sec 3.1 cosets and Lagrange's theorem, cited by name. Artin, Algebra, 2nd ed 2011, ch 2 groups and the symmetry chapter for the dihedral vocabulary, cited by name. Wikipedia, Lagrange's theorem (group theory), en.wikipedia.org/wiki/Lagrange%27s\_theorem\_(group\_theory), the divisor statement, the $|G| = [G : H] dot |H|$ variant, the left-coset partition proof, the element corollary a^n = e, and the A4 counterexample to the converse, fetched 2026-09-21. Wikipedia, cyclic group, en.wikipedia.org/wiki/Cyclic\_group, ord(m in Z/nZ) = n/gcd(n,m), generators are the residues coprime to n with count phi(n), the klein U(8), and U(p) cyclic for prime p, fetched 2026-09-21. Wikipedia, multiplicative group of integers modulo n, en.wikipedia.org/wiki/Multiplicative\_group\_of\_integers\_modulo\_n, |U(n)| = phi(n) and the gauss classification n = 1, 2, 4, p^k, 2p^k, fetched 2026-09-21. Wikipedia, dihedral group of order 6, en.wikipedia.org/wiki/Dihedral\_group\_of\_order\_6, D3 isomorphic to S3, the smallest non-abelian group, six transformations of an equilateral triangle, fetched 2026-09-21. Expected values computed with python exact integers in the one-off playground/math-ch16/gen.py. Sample behavior verified by `pwsh -NoProfile -File tools/run-c-samples.ps1 -SampleRoot books/math/samples/src -Chapter Ch16`, 58 checks in chapter 16 of the math suite, probed on this machine 2026-09-21.
