// book 9 manifest: chapter registry used by cross references and stubs
#let dsabook = (
  num: 9,
  volume: false,
  title: "practical data structures and algorithms",
  meta: (
    title: "practical data structures and algorithms",
    subtitle: "an engineering handbook in seven languages",
    author: "Raeliosol",
    version: "8.0",
    volume-label: "book 9",
  ),
  chapters: (
    (id: "analysis", num: 1, title: "complexity analysis and honest benchmarking"),
    (id: "arrays", num: 2, title: "arrays, spans, memory layout"),
    (id: "dynamicarrays", num: 3, title: "dynamic arrays and amortization"),
    (id: "linked", num: 4, title: "linked structures"),
    (id: "stacksqueues", num: 5, title: "stacks, queues, deques"),
    (id: "hashing", num: 6, title: "hashing"),
    (id: "trees", num: 7, title: "trees"),
    (id: "heaps", num: 8, title: "heaps and priority queues"),
    (id: "tries", num: 9, title: "tries and suffix structures"),
    (id: "graphs", num: 10, title: "graphs"),
    (id: "shortestpaths", num: 11, title: "shortest paths"),
    (id: "mstflows", num: 12, title: "minimum spanning trees and flows"),
    (id: "sorting", num: 13, title: "sorting"),
    (id: "searching", num: 14, title: "searching and answer spaces"),
    (id: "stringmatching", num: 15, title: "string matching"),
    (id: "numtheory", num: 16, title: "number theory and modular arithmetic"),
    (id: "dp", num: 17, title: "dynamic programming"),
    (id: "greedy", num: 18, title: "greedy and backtracking"),
    (id: "advdp", num: 19, title: "advanced dynamic programming"),
    (id: "pruning", num: 20, title: "pruning and branch and bound"),
    (id: "ranges", num: 21, title: "range queries"),
    (id: "compression", num: 22, title: "coordinate compression and intervals"),
    (id: "geometry", num: 23, title: "computational geometry"),
    (id: "lattice", num: 24, title: "lattice geometry and grid algorithms"),
    (id: "practical", num: 25, title: "practical structures"),
    (id: "parsing", num: 26, title: "parsing and asts"),
    (id: "interpreter", num: 27, title: "an opcode machine"),
    (id: "numtheory2", num: 28, title: "advanced number theory"),
    (id: "fastarith", num: 29, title: "fast big arithmetic"),
    (id: "balanced", num: 30, title: "balanced trees and order statistics"),
    (id: "blocks", num: 31, title: "sqrt decomposition and offline queries"),
    (id: "advdp2", num: 32, title: "dynamic programming ii"),
    (id: "strings2", num: 33, title: "string algorithms ii"),
    (id: "linalg", num: 34, title: "linear algebra"),
    (id: "combinatorics", num: 35, title: "combinatorics"),
    (id: "numerical", num: 36, title: "numerical methods"),
    (id: "geometry2", num: 37, title: "computational geometry ii"),
    (id: "flows2", num: 38, title: "network flows ii"),
    (id: "connectivity", num: 39, title: "graph connectivity and decomposition"),
    (id: "games", num: 40, title: "game theory and scheduling"),
    (id: "metaheuristics", num: 41, title: "local search and metaheuristics"),
    (id: "approximation", num: 42, title: "approximation algorithms"),
    (id: "finegrained", num: 43, title: "fine-grained speedups"),
    (id: "capstone", num: 44, title: "capstone: storage engine toolkit"),
    (id: "appendices", num: 45, title: "appendices: topic matrix and sources"),
  ),
)
