mkdir -p ~/work/.vscode/data ~/work/.vscode/extensions
cp settings.json keybindings.json ~/work/.vscode/data/User
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension aaron-bond.better-comments
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension andyyu2004.vscode-neovim
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension bierner.markdown-preview-github-styles
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension bradlc.vscode-tailwindcss
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension christian-kohler.path-intellisense
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension ckolkman.vscode-postgres
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension DavidAnson.vscode-markdownlint
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension dbaeumer.vscode-eslint
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension doggy8088.quicktype-refresh
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension eamodio.gitlens
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension EditorConfig.EditorConfig
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension emilast.LogFileHighlighter
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension esbenp.prettier-vscode
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension foxundermoon.shell-format
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension GitHub.copilot
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension GitHub.github-vscode-theme
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension GitHub.remotehub
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension GitHub.vscode-pull-request-github
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension golang.go
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension Gruntfuggly.todo-tree
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension jameslan.yaclock
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension janisdd.vscode-edit-csv
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension mechatroner.rainbow-csv
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension mhutchie.git-graph
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension mikestead.dotenv
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension mongodb.mongodb-vscode
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension ms-azuretools.vscode-docker
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension ms-vscode.remote-repositories
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension ms-vsliveshare.vsliveshare
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension ms-vsliveshare.vsliveshare-audio
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension ms-vsliveshare.vsliveshare-pack
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension mutantdino.resourcemonitor
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension pascalsenn.keyboard-quickfix
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension plex.vscode-protolint
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension RandomFractalsInc.vscode-data-preview
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension redhat.vscode-yaml
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension softwaredotcom.swdc-vscode
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension streetsidesoftware.code-spell-checker
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension usernamehw.errorlens
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension VisualStudioExptTeam.vscodeintellicode
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension vscode-icons-team.vscode-icons
code --user-data-dir ~/work/.vscode/data --extensions-dir ~/work/.vscode/extensions --install-extension zxh404.vscode-proto3
echo "setup finished!"
