local wezterm = require 'wezterm';
return {
  font = wezterm.font_with_fallback({
    "Iosevka Nerd Font",
    "FiraCode Nerd Font",
  }),
  font_size = 10,
  --color_scheme = "Gruvbox Dark",
  --color_scheme = "Andromeda",
  --color_scheme = "nord",
  --color_scheme = "Nord Deep",
  --color_scheme = "Aura Dark",
  color_scheme = "wezterm_github_dark_brighten",
  --color_scheme = "Tinacious Design (Dark)",
  --color_scheme = "wezterm_tokyonight_night",
  --color_scheme = "wezterm_tokyonight_day",
  --color_scheme = "Alabaster",
  color_schemes = {
    ["Nord Deep"] = {
      foreground = "#d8dee9",
      background = "#232731",
      cursor_bg = "#eceff4",
      cursor_border = "#eceff4",
      cursor_fg = "#282828",
      selection_bg = "#eceff4",
      selection_fg = "#4c566a",
      ansi = {"#3b4252","#bf616a","#a3be8c","#ebcb8b","#81a1c1","#b48ead","#88c0d0","#e5e9f0"},
      brights = {"#4c566a","#bf616a","#a3be8c","#ebcb8b","#81a1c1","#b48ead","#8fbcbb","#eceff4"},
    },

    ["Aura Dark"] = {
      foreground = "#a277ff",
      background = "#15141b",
      cursor_bg = "#edecee",
      cursor_border = "#edecee",
      cursor_fg = "#3d375e",
      selection_bg = "#edecee",
      selection_fg = "#3d375e",
    },
  },
  enable_scroll_bar = true,
  keys = {
    {key="=", mods="ALT", action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
    {key="+", mods="ALT|SHIFT", action=wezterm.action{SplitVertical={domain="CurrentPaneDomain"}}},
    {key="w", mods="CTRL", action=wezterm.action{CloseCurrentPane={confirm=true}}},
    {key="1", mods="ALT", action=wezterm.action{ActivateTab=0}},
    {key="2", mods="ALT", action=wezterm.action{ActivateTab=1}},
    {key="3", mods="ALT", action=wezterm.action{ActivateTab=2}},
    {key="4", mods="ALT", action=wezterm.action{ActivateTab=3}},
    {key="5", mods="ALT", action=wezterm.action{ActivateTab=4}},
    {key="6", mods="ALT", action=wezterm.action{ActivateTab=5}},
    {key="7", mods="ALT", action=wezterm.action{ActivateTab=6}},
    {key="8", mods="ALT", action=wezterm.action{ActivateTab=7}},
    {key="h", mods="ALT", action=wezterm.action{ActivatePaneDirection="Left"}},
    {key="l", mods="ALT", action=wezterm.action{ActivatePaneDirection="Right"}},
    {key="k", mods="ALT", action=wezterm.action{ActivatePaneDirection="Up"}},
    {key="j", mods="ALT", action=wezterm.action{ActivatePaneDirection="Down"}},
  },
}

