// book 6 manifest: chapter registry used by cross references and stubs
#let jsbook = (
  num: 6,
  volume: false,
  title: "javascript es2026 and typescript 7",
  meta: (
    title: "javascript es2026 and typescript 7",
    subtitle: "a complete manual for two layers",
    author: "Mr. Raheliosol",
    version: "6.1",
    volume-label: "book 6",
  ),
  // the book is javascript first: chapters 1-10 are the runtime
  // without a build step, 11-20 the typescript layer, 21-22 the
  // framework layer where vite enters, the service part holds
  // 23-35, 36-37 the typed layer over the same vehicle, 38 the
  // capstone, 39 appendices.
  chapters: (
    (id: "toolchain", num: 1, title: "javascript and its toolchain"),
    (id: "lexical", num: 2, title: "values and lexical structure"),
    (id: "functions", num: 3, title: "functions, scope, and closures"),
    (id: "objects", num: 4, title: "objects, prototypes, and classes"),
    (id: "iteration", num: 5, title: "iteration and collections"),
    (id: "async", num: 6, title: "async javascript"),
    (id: "modules", num: 7, title: "modules and resources"),
    (id: "stdlib", num: 8, title: "the standard library by edition"),
    (id: "heap", num: 9, title: "the heap and the collector"),
    (id: "profiling", num: 10, title: "profiling and the event-loop tail"),
    (id: "tstoolchain", num: 11, title: "typescript 7: the type layer"),
    (id: "typesyntax", num: 12, title: "type syntax"),
    (id: "types", num: 13, title: "the type landscape"),
    (id: "typefunctions", num: 14, title: "typing functions"),
    (id: "typeobjects", num: 15, title: "typing objects"),
    (id: "unions", num: 16, title: "unions and narrowing"),
    (id: "typelevel", num: 17, title: "type-level programming"),
    (id: "typeclasses", num: 18, title: "classes and decorators"),
    (id: "typemodules", num: 19, title: "declarations, namespaces, and emit"),
    (id: "idioms", num: 20, title: "typescript idioms"),
    (id: "react", num: 21, title: "react 19: components as functions"),
    (id: "svelte", num: 22, title: "svelte 5: runes and compiled reactivity"),
    (id: "api-kernel", num: 23, title: "api kernel"),
    (id: "middleware", num: 24, title: "middleware"),
    (id: "users", num: 25, title: "the user resource"),
    (id: "authn", num: 26, title: "authn"),
    (id: "authz", num: 27, title: "authz and rbac"),
    (id: "store", num: 28, title: "store"),
    (id: "conc", num: 29, title: "concurrency control"),
    (id: "cache", num: 30, title: "caching"),
    (id: "limit", num: 31, title: "rate limiting"),
    (id: "obs", num: 32, title: "observability"),
    (id: "load", num: 33, title: "load and p99"),
    (id: "shipit", num: 34, title: "ship it"),
    (id: "suite", num: 35, title: "the test suite"),
    (id: "typed", num: 36, title: "the typed layer"),
    (id: "typedsuite", num: 37, title: "the typed suite"),
    (id: "capstone", num: 38, title: "capstone: the query engine, microfrontend"),
    (id: "appendices", num: 39, title: "appendices: coverage and sources"),
  ),
)
