# Generate code coverage report and badge for the repository
param(
    [switch]$UpdateReadme,
    [switch]$Verbose
)

Import-Module Pester

Write-Host "`n=== Code Coverage Report ===`n"

# Bash Coverage (read from actual measurement if available)
Write-Host "Calculating Bash coverage..."

$bashCoverage = 0.0
$bashMethod = "estimated"

# Try to read from coverage-bash.json (generated by tests/coverage.sh)
if (Test-Path "coverage-bash.json") {
    $bashData = Get-Content "coverage-bash.json" -Raw | ConvertFrom-Json
    $bashCoverage = [math]::Round($bashData.bash_coverage, 1)
    $bashMethod = $bashData.tool
    Write-Host "  Bash: $bashCoverage% (measured via $bashMethod)"
}
elseif (Test-Path "coverage.json") {
    $coverageData = Get-Content "coverage.json" -Raw | ConvertFrom-Json
    if ($coverageData.bash_coverage) {
        $bashCoverage = [math]::Round($coverageData.bash_coverage, 1)
        $bashMethod = if ($coverageData.bash_method) { $coverageData.bash_method } else { "json" }
        Write-Host "  Bash: $bashCoverage% (from coverage.json)"
    }
}
else {
    # Fallback to estimate (not recommended)
    $bashCoverage = 25.0
    Write-Host "  Bash: $bashCoverage% (estimated - run tests/coverage.sh for actual)"
    Write-Warning "Run 'bash tests/coverage.sh' first to get actual bash coverage"
}

# PowerShell Coverage
Write-Host "Calculating PowerShell coverage..."
$config = [PesterConfiguration]::Default
$config.CodeCoverage.Enabled = $true
$config.CodeCoverage.Path = @(
    "bootstrap\lib\common.ps1",
    "hooks\git\pre-commit.ps1",
    "hooks\git\commit-msg.ps1",
    "deploy.ps1",
    "update-all.ps1"
)
$config.Run.Path = 'tests\powershell'
$config.Run.PassThru = $true
$config.Output.Verbosity = 'None'

$psResult = Invoke-Pester -Configuration $config
$psCoverage = [math]::Round($psResult.CodeCoverage.CoveragePercent, 1)
Write-Host "  PowerShell: $psCoverage% ($($psResult.CodeCoverage.CommandsExecutedCount)/$($psResult.CodeCoverage.CommandsAnalyzedCount) commands)"

# Combined coverage (weighted average)
# Weighted by script complexity (rough estimate)
$combinedCoverage = [math]::Round(($psCoverage * 0.6) + ($bashCoverage * 0.4), 1)
Write-Host "`n  Combined: $combinedCoverage%"

# Determine badge color (shields.io named colors)
if ($combinedCoverage -ge 80) { $badgeColor = "brightgreen" }
elseif ($combinedCoverage -ge 70) { $badgeColor = "green" }
elseif ($combinedCoverage -ge 60) { $badgeColor = "yellowgreen" }
elseif ($combinedCoverage -ge 50) { $badgeColor = "yellow" }
elseif ($combinedCoverage -ge 40) { $badgeColor = "orange" }
else { $badgeColor = "red" }

# Generate SVG badge
$badgeSvg = @"
<svg xmlns="http://www.w3.org/2000/svg" width="160" height="20" role="img" aria-label="Code coverage: $combinedCoverage%">
  <title>Code coverage: $combinedCoverage%</title>
  <linearGradient id="s" x2="0" y2="100%">
    <stop offset="0%" stop-color="#bbb" stop-opacity=".1"/>
    <stop offset="1%" stop-opacity=".1"/>
    <stop offset="100%" stop-color="#555" stop-opacity=".1"/>
  </linearGradient>
  <g class="nc">
    <rect x="0" width="95" height="20" fill="#555"/>
    <rect x="95" width="65" height="20" fill="#$badgeColor"/>
    <rect width="160" height="20" fill="url(#s)"/>
  </g>
  <g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="11">
    <text x="48" y="15" fill="#010101" fill-opacity=".3">coverage</text>
    <text x="48" y="14">coverage</text>
    <text x="127" y="15" fill="#010101" fill-opacity=".3">$combinedCoverage%</text>
    <text x="127" y="14">$combinedCoverage%</text>
  </g>
</svg>
"@

# Save badge
$badgePath = "coverage-badge.svg"
$badgeSvg | Out-File $badgePath -Encoding UTF8
Write-Host "`nBadge saved to: $badgePath"

# Save coverage data
$coverageData = @{
    ps_coverage = $psCoverage
    bash_coverage = $bashCoverage
    combined_coverage = $combinedCoverage
    timestamp = Get-Date -Format "o"
} | ConvertTo-Json -Depth 10

$coverageData | Out-File "coverage.json" -Encoding UTF8
Write-Host "Coverage data saved to: coverage.json"

# Update README if requested
if ($UpdateReadme) {
    $readmePath = "README.md"
    $readmeContent = Get-Content $readmePath -Raw

    # Generate shields.io badge URL
    $badgeUrl = "https://img.shields.io/badge/coverage-$([math]::Floor($combinedCoverage))%25-$badgeColor"
    $badgeMarkdown = "![Coverage]($badgeUrl)"

    # Check if coverage badge already exists
    $badgePattern = '!\[Coverage\]\(https://img\.shields\.io/badge/coverage-[^)]+\)'

    if ($readmeContent -match $badgePattern) {
        # Update existing badge
        $readmeContent = $readmeContent -replace $badgePattern, "![Coverage]($badgeUrl)"
        Write-Host "`nUpdated coverage badge in README.md"
    } else {
        # Add badge after the title
        $readmeContent = $readmeContent -replace "(# Universal Dotfiles)`n", "`$1`n$badgeMarkdown `n"
        Write-Host "`nAdded coverage badge to README.md"
    }

    $readmeContent | Out-File $readmePath -Encoding UTF8 -NoNewline
}

Write-Host "`n=== Summary ==="
Write-Host "PowerShell: $psCoverage%"
Write-Host "Bash: $bashCoverage% (via $bashMethod)"
Write-Host "Combined: $combinedCoverage%"
