// book 11 manifest: chapter registry used by cross references and stubs
#let infrastructure = (
  num: 11,
  volume: false,
  title: "infrastructure: docker, databases, and testing",
  meta: (
    title: "infrastructure: docker, databases, and testing",
    subtitle: "an engineering handbook",
    author: "gabriel la",
    version: "2.0",
    volume-label: "book 11",
  ),
  chapters: (
    (id: "toolchain", num: 1, title: "the toolchain: docker on windows"),
    (id: "images", num: 2, title: "images and layers"),
    (id: "containers", num: 3, title: "containers: processes, signals, pid 1"),
    (id: "compose", num: 4, title: "compose and one click local systems"),
    (id: "networking", num: 5, title: "container networking"),
    (id: "sqlite-schema", num: 6, title: "sqlite: schemas and normalization"),
    (id: "sqlite-transactions", num: 7, title: "sqlite: transactions and isolation"),
    (id: "sqlite-wal", num: 8, title: "sqlite: wal, locking, crash semantics"),
    (id: "sqlite-features", num: 9, title: "sqlite: the 3.53 feature set"),
    (id: "sqlite-production", num: 10, title: "sqlite in production: embedded kvs and game saves"),
    (id: "duckdb", num: 11, title: "duckdb: the embedded analytical engine"),
    (id: "duckdb-sqlite", num: 12, title: "duckdb and sqlite together: choosing the engine"),
    (id: "mongo", num: 13, title: "mongodb and aggregation pipelines"),
    (id: "nats", num: 14, title: "nats: pub sub, request reply, queue groups"),
    (id: "jetstream", num: 15, title: "jetstream: streams, consumers, kv, kafka compared"),
    (id: "testing", num: 16, title: "testing without docker"),
    (id: "mocks", num: 17, title: "mocks, seeding, contract tests"),
    (id: "migrations", num: 18, title: "migrations, test driven"),
    (id: "capstone1", num: 19, title: "capstone part 1: services and topology"),
    (id: "capstone2", num: 20, title: "capstone part 2: chat and notifications, one click"),
  ),
)
