// book 7 manifest: chapter registry used by cross references and stubs
#let pybook = (
  num: 7,
  volume: false,
  title: "python 3.14",
  meta: (
    title: "python 3.14",
    subtitle: "a complete language manual",
    author: "Mr. Raheliosol",
    version: "4.0",
    volume-label: "book 7",
  ),
  chapters: (
    (id: "toolchain", num: 1, title: "toolchain: cpython 3.14 on windows"),
    (id: "lexical", num: 2, title: "lexical structure"),
    (id: "objects", num: 3, title: "the object model"),
    (id: "collections", num: 4, title: "builtin collections, iteration, and generators"),
    (id: "strings", num: 5, title: "strings, bytes, and text"),
    (id: "functions", num: 6, title: "functions, scopes, and decorators"),
    (id: "classes", num: 7, title: "classes and inheritance"),
    (id: "typing", num: 8, title: "the typing system"),
    (id: "dataclasses", num: 9, title: "dataclasses, enums, and pattern matching"),
    (id: "exceptions", num: 10, title: "exceptions and context managers"),
    (id: "modules", num: 11, title: "modules, packages, and imports"),
    (id: "interpreter", num: 12, title: "how cpython runs your code"),
    (id: "pymalloc", num: 13, title: "pymalloc: arenas, freelists, and tracemalloc"),
    (id: "profiling", num: 14, title: "profiling: cprofile, sys.monitoring, and p99"),
    (id: "files", num: 15, title: "files and serialization"),
    (id: "processes", num: 16, title: "os, subprocess, and signals"),
    (id: "threads", num: 17, title: "threads and the gil"),
    (id: "multiprocessing", num: 18, title: "multiprocessing and process patterns"),
    (id: "plumbing", num: 19, title: "operational plumbing"),
    (id: "testing", num: 20, title: "testing with unittest"),
    (id: "asyncio", num: 21, title: "asyncio"),
    (id: "fastapi", num: 22, title: "fastapi"),
    (id: "numerics", num: 23, title: "stdlib numerics: math, statistics, decimal, random"),
    (id: "numpy", num: 24, title: "numpy"),
    (id: "pandas", num: 25, title: "pandas"),
    (id: "pydantic", num: 26, title: "pydantic"),
    (id: "http-kernel", num: 27, title: "http kernel"),
    (id: "middleware", num: 28, title: "middleware"),
    (id: "users", num: 29, title: "the user resource"),
    (id: "authn", num: 30, title: "authn"),
    (id: "authz", num: 31, title: "authz and rbac"),
    (id: "store", num: 32, title: "store"),
    (id: "conc", num: 33, title: "concurrency control"),
    (id: "cache", num: 34, title: "caching"),
    (id: "limit", num: 35, title: "rate limiting"),
    (id: "obs", num: 36, title: "observability"),
    (id: "load", num: 37, title: "load and p99"),
    (id: "shipit", num: 38, title: "ship it"),
    (id: "suite", num: 39, title: "the test suite"),
    (id: "capstone1", num: 40, title: "capstone: ingest and analysis pipeline, part 1"),
    (id: "capstone2", num: 41, title: "capstone: ingest and analysis pipeline, part 2"),
    (id: "appendices", num: 42, title: "appendices: coverage and sources"),
  ),
)
