#import "../../theme/lib.typ": listing, snippet, callout, diagram, flow, cdraw, xref-to
#import "@preview/fletcher:0.5.8": node, edge

#let pane(x0, x1, ytop, title, ..lines) = {
  let ls = lines.pos()
  cdraw.rect((x0, ytop - 2.3 - (ls.len() - 1) * 1.1), (x1, ytop), fill: luma(235), radius: 0.02)
  cdraw.content(((x0 + x1) / 2, ytop - 0.6), [#title], size: 6.5pt)
  for (i, l) in ls.enumerate() {
    cdraw.content(((x0 + x1) / 2, ytop - 1.75 - i * 1.1), [#l], size: 6pt)
  }
}

= functional java

Java 8 (JSR 335) made functions values: lambdas, method references,
and a function package of target types. The design kept java nominal,
there is no function type in the language, only interfaces with one
abstract method, and the compile story is unlike any other feature's:
lambdas do not become anonymous classes, they become
`invokedynamic` calls into `LambdaMetafactory`, which materializes a
lightweight class at first use. Everything in this chapter measures
that story on the pinned build.

== the function package

The target types live in `java.util.function`, and the census is a
fact, not a guess: 43 top-level interfaces on jdk 27, counted live
from the jrt filesystem, every one carrying `@FunctionalInterface`
and exactly one abstract method:

#listing("java/samples/src/Ch08/Inventory.java", first: 25, last: 37, caption: [the census, walked straight out of the runtime image])

Four shapes cover most code: `Function<T, R>` transforms, `Predicate<T>`
tests, `Supplier<T>` produces, `Consumer<T>` consumes. `BiFunction`
takes two, `UnaryOperator` and `BinaryOperator` stay in one type, and
the primitive specializations, `IntFunction`, `ToLongFunction`,
`IntPredicate` and friends, exist because type parameters cannot hold
primitives, chapter 6. The shapes compose:

#listing("java/samples/src/Ch08/Inventory.java", first: 59, last: 66, caption: [andThen, compose, negate, and the identities])

`andThen` reads left to right, `compose` right to left, and
`Function.identity` is the unit of composition. A functional
interface is still an interface: default methods may pile up, exactly
one method may stay abstract:

#listing("java/samples/src/Ch08/Inventory.java", first: 39, last: 52, caption: [the sam rule checked by reflection over the core shapes])

`@FunctionalInterface` is optional documentation with teeth, the
compiler rejects a second abstract method on an annotated type, and
chapter 7 measured it as `RUNTIME` retention.

== the lambda compile story

A lambda is a function literal with no name of its own, `(p, q) ->
body`, converted to whatever functional interface the context expects.
The conversion is target typing, the compiler reads the assignment or
parameter position to know what to build. What it builds is the part
worth knowing, and the sample reads it back through reflection:

#listing("java/samples/src/Ch08/Lambdas.java", first: 29, last: 42, caption: [one lambda and one anonymous class, named by the runtime])

The anonymous class is `Lambdas$1`, a real class file with a name
slot, emitted by `javac` per source occurrence. The lambda's class is
`Lambdas$$Lambda/0x...`, synthetic, generated by the metafactory at
first use, and its name carries a runtime identity because there is no
source-level one. C\#'s lambdas compile to delegates, a first-class
runtime function type, #xref-to("csharp-net", "delegates") walks that design. Java chose
dynamic linkage instead, the same machinery the string concat and
later record bootstrap reuse, and it is why a lambda costs nothing
until called and why `this` inside one means the enclosing object,
chapter 7 measured that split.

== method references

A method reference is a lambda with the body borrowed from an
existing method, `String::length` for `s -> s.length()`. Four kinds,
by what is fixed:

#listing("java/samples/src/Ch08/MethodRefs.java", first: 26, last: 43, caption: [unbound, bound, static, constructor, plus the array constructor])

The unbound kind has the one rule that bites: the receiver must
arrive as the first parameter of the functional shape. Measured on
the pinned build, `Thread::threadId` against `Supplier<Long>` fails
compilation with `unexpected instance method threadId() found in
unbound lookup`, because a supplier has no parameter to be the
receiver. The same reference against `ToLongFunction<Thread>` compiles
cleanly:

#listing("java/samples/src/Ch08/MethodRefs.java", first: 50, last: 57, caption: [the shape supplies the receiver slot, and the reference fits])

#snippet(
  "// measured 2026-10-04 on build 27+35-2325, refuses to compile:\n"
  + "Supplier<Long> tid = Thread::threadId;\n"
  + "// error: incompatible types: invalid method reference\n"
  + "//   unexpected instance method threadId() found in unbound lookup\n",
  lang: "java",
)

== capture and the effectively final rule

A lambda body may read local variables of the enclosing scope, but
only ones it can treat as constants: captured locals must be final or
effectively final, assigned once, because the capture is a copy of the
value, and a mutable copy would diverge from the variable silently.
The compile error on a reassigned capture is the language refusing
that divergence. The sample builds closures that outlive their scope,
the classic loop:

#listing("java/samples/src/Ch08/Lambdas.java", first: 44, last: 53, caption: [three closures over three values of one loop variable])

Each snapshot holds its own copy, and the copies stay correct after
the loop is gone. The copy is of the variable's value, so for a
reference that means the reference is frozen while the object it
points at remains mutable:

#listing("java/samples/src/Ch08/Lambdas.java", first: 55, last: 62, caption: [the array reference frozen, its contents live])

That asymmetry is the daily shape of java closures: state you can
close over is state you can only reach through, never reassign. A
mutable counter needs a holder, an array as here or an
`AtomicInteger` in real code, chapter 10 owns the thread story.

== Optional as a return contract

`Optional<T>` is a container that may be empty, designed for one
narrow job: return types, so an absent result is a value instead of a
null test. The core discipline is to never call `get` on a maybe
empty, and the api gives better tools for every case:

#listing("java/samples/src/Ch08/Optionals.java", first: 24, last: 46, caption: [of, empty, map, orElse, orElseGet, and the two throws])

The laziness difference is measurable: `orElse` computes its argument
eagerly, present or not, `orElseGet` only on absence. In the run the
eager default fired once with a present value, the lazy one not at
all. `of(null)` throws immediately, `ofNullable` guards the nullable
boundary, and `get` on empty throws `NoSuchElementException`, the
runtime's answer to skipping the contract:

#listing("java/samples/src/Ch08/Optionals.java", first: 47, last: 64, caption: [the failure paths, measured rather than asserted from memory])

#callout("note", "optional is a return type", [
  Fields, parameters, and collection elements should not be optional.
  An `Optional` field holds a reference to another object for no
  information gain, and `Optional.get` in a chain is just a null test
  with more steps. Return it, consume it immediately, never store it.
])

== the stream pipeline

Streams compose the function shapes over data. A pipeline is a
source, zero or more lazy intermediate operations, and one terminal
operation that pulls everything through:

#flow(
  [one pipeline, one pull],
  node((0, 0), [source, #linebreak() stream.of, iterate, #linebreak() a collection]),
  edge("-|>"),
  node((2.2, 0), [intermediates, #linebreak() map, filter, limit: #linebreak() lazy, build only]),
  edge("-|>"),
  node((4.6, 0), [terminal, #linebreak() tolist, foreach, #linebreak() findfirst: the pull]),
  edge((4.6, 0), (4.6, -1.2), "-|>"),
  node((4.6, -1.2), [values flow back through, #linebreak() one element at a time]),
)

The laziness is not a claim, the sample traces it. Building the
pipeline runs nothing. The terminal call drives every stage, and each
element traverses the whole pipeline before the next one starts,
which is why a `filter` cannot be talked about before or after
ordering the way sql clauses can:

#listing("java/samples/src/Ch08/Lazy.java", first: 27, last: 40, caption: [the empty trace before the terminal, the per-element interleave after])

Short-circuiting terminals stop the pull early, `findFirst` leaves
the third element unmapped, and `limit` terminates an infinite
source, the sample builds the first three even numbers from
`Stream.iterate`:

#listing("java/samples/src/Ch08/Lazy.java", first: 42, last: 56, caption: [findFirst stops the pull, limit caps an infinite source])

Chapter 12 owns streams in full, the collectors, the parallel
variants, and the java 24 gatherers. What belongs here is the
composition model: a stream is a description of work that never runs
until asked, and an unused pipeline is garbage, not computation.

sources: Java in a Nutshell 8th edition, chapter 4 lambda expressions
and chapter 8 streams, pages 180 to 187 and 306 to 317. JEP and
release spine from docs/audit/java.md, checked 2026-10-04. Every
behavioral claim is asserted by `java/samples/src/Ch08`, 34 checks
green under `pwsh -NoProfile -File tools/run-java-samples.ps1
-Chapter Ch08` on the pinned build 27+35-2325, measured 2026-10-04.
