#import "../../theme/lib.typ": listing, snippet, callout, diagram, cdraw

= reflection and method handles

Reflection is the runtime looking at types it did not know at compile
time: what methods a class has, what annotations sit on them, how to
build an instance from a name. Every framework that wires objects
together, every test runner, every serializer, is reflection
underneath. Java grew two answers to it, the 1996
`java.lang.reflect` api and the java 7 `java.lang.invoke` api, method
handles, built for `invokedynamic` and now the machinery under every
lambda. This chapter walks both, then the hardening arc, records that
refuse mutation since 16 and the final means final warning since 26.

== class objects

A `Class` object is a live type inside the running process, and there
are three doors into one, a literal, `getClass`, and a lookup by
name:

#listing("java/samples/src/Ch16/Reflect.java", first: 59, last: 74, caption: [one class object per type, wrappers distinct from primitives, records visible])

Primitives participate: `int.class` and `Integer.TYPE` are the same
object, `Integer.class` is a different one, and the awkward
`Object[]` based api shows its age right there. The class object
carries the metadata the compiler used, constructors, fields, method
signatures, annotations, and the reflective api is a walk over that
metadata.

== invoking and constructing

The workhorse is `Method`. `getMethod` returns public methods,
`getDeclaredMethod` reaches the private ones after `setAccessible`,
and `invoke` calls with an `Object[]` for arguments, boxing the
primitives both ways:

#listing("java/samples/src/Ch16/Reflect.java", first: 75, last: 83, caption: [invoke boxes the return, the constructor builds the record])

Constructors are methods without names, found by parameter types,
`Constructor.newInstance` builds without `new`. The old shortcut
`Class.newInstance` is deprecated since java 9, and the annotation on
it is itself readable reflectively, which is the next subject.

== annotations at runtime

An annotation only exists at runtime if its retention policy says
so, `RetentionPolicy.RUNTIME`. Class file retention, the default,
keeps it for compilers and tools but reflection cannot see it. The
runtime-retained ones come back as proxy objects generated by the
same machinery as the last section of this chapter:

#listing("java/samples/src/Ch16/Reflect.java", first: 84, last: 94, caption: [a custom runtime annotation, and the jdk's own deprecation metadata])

== records and the reflective contract

Records, final since java 16, are transparent data carriers and the
reflection api knows it: `isRecord` and `getRecordComponents` expose
the component list, name and type, that generated the accessor,
`equals`, `hashCode`, and `toString`. The contract cuts the other way
too, the components are truly final. `setAccessible(true)` on a
record field succeeds, and the write still throws
`IllegalAccessException`, measured in the sample, because the
language promised the fields never change after construction. That
promise is what makes records safe as map keys and value objects.

== final means final

Records were the first hardening step. Java 26 (JEP 500) extends the
same discipline to every final field, reflectively writable since 1.2
for serialization and mocking frameworks, and now on a removal path.
On this build the mutation still works, but it warns:

#listing("java/samples/src/Ch16/Reflect.java", first: 113, last: 139, caption: [the subprocess probe compiling and running the mutation, capturing the warning])

The measured warning names the field, the class, and the caller's
module, points at `--enable-final-field-mutation=ALL-UNNAMED` as the
opt out, and states the schedule, a future release denies by default.
`--illegal-final-field-mutation=deny` front-runs that today,
`Field.set` and `MethodHandles.Lookup.unreflectSetter` then throw
`IllegalAccessException`, and a JFR event records offenders. The
warning cannot be silenced with `--add-opens`, opening a package
grants access, not mutation rights.

#callout("pitfall", "constant folding hides the mutation", [
  A `final int f = 1` initialized with a constant expression is a
  constant variable, and javac inlines reads of it at the use site.
  Reflectively mutated or not, the direct expression still prints 1,
  because the class reading it never looked at the field. Half the
  folklore that reflective final mutation works is this illusion.
])

== dynamic proxies

`Proxy.newProxyInstance` builds a class at runtime that implements an
interface and routes every call, including `toString`, `equals`, and
`hashCode`, to one `InvocationHandler`:

#listing("java/samples/src/Ch16/Reflect.java", first: 141, last: 155, caption: [one handler answers an interface with a switch over method names])

Proxies are the smallest mock framework and the core of chapter 18's
test doubles discussion. They only proxy interfaces, the handler is
the entire implementation, and since java 16 that handler is usually
one lambda with a switch over the method name.

== method handles

Method handles are the second reflection, designed not for
frameworks looking at unknown types but for call sites that change
their target at runtime, and `invokedynamic`, the bytecode instruction
behind every lambda since java 8. The type of a handle is a
`MethodType`, return type first, argument types after, no method
name and no receiver, because any method of that shape can ride it:

#listing("java/samples/src/Ch16/Handles.java", first: 26, last: 53, caption: [method types, lookup, findVirtual and findStatic, asType and bindTo])

The big difference from `java.lang.reflect` is access control. A
`Lookup` object is created at a specific call site, `MethodHandles.lookup()`,
and it can only find what that site could have written
`someMethod` for. There is no `setAccessible` equivalent and no way
to subvert it, which is why the same jdk can offer handles to
untrusted frameworks. Composition is the other strength, `asType`
adapts signatures, `bindTo` pins a receiver, `filterArguments` and
`collectArguments` reshape pipelines, operations that on
`java.lang.reflect` would be manual array shuffling.

The cost story, measured on this machine, best of five rounds of a
million calls, 2026-10-04:

#diagram([call mechanisms by measured cost, nanoseconds per call, lower is better], length: 13pt, {
  let rows = (("direct", 0.29), ("lambda", 0.29), ("handle exact", 2.58), ("handle generic", 3.43), ("reflection", 5.78))
  for (i, r) in rows.enumerate() {
    let y = 7 - i * 1.5
    cdraw.rect((2.0, y - 0.45), (2.0 + r.at(1) * 4.4, y + 0.45), fill: luma(205), radius: 0.02)
    cdraw.content((1.6, y), [#r.at(0)], size: 6pt, anchor: "east")
    cdraw.content((2.4 + r.at(1) * 4.4, y), [#r.at(1)], size: 6pt, anchor: "west")
  }
  cdraw.content((11.8, -0.6), [reflection 5.78 ns, exact handle 2.58, direct and lambda 0.29], size: 6pt)
})

#callout("verify", "micro numbers, read with care", [
  These are best-of-five nanoseconds on one machine with the jit
  warm, printed by the `Handles` sample each run. The honest claims
  are the shape, direct and lambda are free after inlining, an exact
  method handle is single digit nanoseconds, the object-typed
  adaptation pays for boxing, and reflection costs about double a
  generic handle. The table on another cpu, or another jdk, shifts.
])

The equality assertion next to the measurement is the part that
matters for correctness, all five paths compute the same sum. When
the mechanism, not the speed, is the reason to reach for handles,
varhandles, the field flavored sibling with memory ordering modes,
are chapter 11 territory.

sources: Java in a Nutshell 8th edition, chapter 11 (Classloading,
Reflection, and Method Handles) for the class object, method,
constructor, proxy, method type, and lookup grounding, rewritten
here, openjdk.org/jeps/500 (prepare to make final mean final, 26)
and /jeps/395 (records final, 16) accessed 2026-10-04, plus the
java 27 javadoc for `Deprecated` annotation attributes. Behavior
verified live on `tools/jdk27/build/jdk-27` by the Ch16 samples
under `pwsh tools/run-java-samples.ps1 -Chapter Ch16`: 28 checks,
Reflect 20 and Handles 8, covering the class object identities, the
boxing round trip, the runtime annotation reads including
`Class.newInstance` since 9 forRemoval false, the record field
refusal after setAccessible, the final field mutation warning
captured from a subprocess with its opt out flag text, the proxy
handler answering object methods, the method type descriptor, and
the five way timing equality, all dated 2026-10-04.
