// book 8 manifest: chapter registry used by cross references and stubs
#let luabook = (
  num: 8,
  volume: false,
  title: "lua 5.5",
  meta: (
    title: "lua 5.5",
    subtitle: "a complete language manual",
    author: "gabriel la",
    version: "5.0",
    volume-label: "book 8",
  ),
  chapters: (
    (id: "toolchain", num: 1, title: "toolchain"),
    (id: "lexical", num: 2, title: "lexical structure"),
    (id: "values", num: 3, title: "values, metatables, metamethods"),
    (id: "expressions", num: 4, title: "expressions and operators"),
    (id: "statements", num: 5, title: "statements and scope"),
    (id: "functions", num: 6, title: "functions"),
    (id: "coroutines", num: 7, title: "coroutines"),
    (id: "environments", num: 8, title: "environments, load, gc"),
    (id: "collector", num: 9, title: "inside the collector"),
    (id: "profiling", num: 10, title: "profiling: hooks, clocks, and p99"),
    (id: "stdlib1", num: 11, title: "stdlib 1: basic, string patterns, utf8"),
    (id: "stdlib2", num: 12, title: "stdlib 2: table, math, io, os"),
    (id: "stdlib3", num: 13, title: "stdlib 3: coroutine, debug, package"),
    (id: "capi", num: 14, title: "the c api, hands on"),
    (id: "incompat", num: 15, title: "incompatibilities with 5.4"),
    (id: "idioms", num: 16, title: "idioms"),
    (id: "ffi", num: 17, title: "ffi: c without the api"),
    (id: "allegro", num: 18, title: "a c host: allegro 5 with lua embedded"),
    (id: "kernel", num: 19, title: "the http kernel"),
    (id: "middleware", num: 20, title: "the middleware chain"),
    (id: "users", num: 21, title: "the user resource"),
    (id: "authn", num: 22, title: "authentication"),
    (id: "authz", num: 23, title: "authorization and roles"),
    (id: "store", num: 24, title: "the store"),
    (id: "conc", num: 25, title: "concurrency control"),
    (id: "cache", num: 26, title: "caching"),
    (id: "limit", num: 27, title: "rate limiting"),
    (id: "obs", num: 28, title: "observability"),
    (id: "load", num: 29, title: "load and p99"),
    (id: "shipping", num: 30, title: "shipping"),
    (id: "suite", num: 31, title: "the test suite"),
    (id: "capstone", num: 32, title: "capstone: auto chess, human versus bot"),
    (id: "appendices", num: 33, title: "appendices: coverage and sources"),
  ),
)
