// book 1 manifest: chapter registry used by cross references and stubs
#let cosbook = (
  num: 1,
  volume: false,
  title: "c23: the language, the machine, and the cloud",
  meta: (
    title: "c23: the language, the machine, and the cloud",
    subtitle: "llvm/clang 23, the operating system, terraform, aws, gcp, and a service",
    author: "gabriel la",
    version: "4.0",
    volume-label: "book 1",
  ),
  chapters: (
    (id: "toolchain", num: 1, title: "toolchain: clang 23 on windows"),
    (id: "lexical", num: 2, title: "lexical structure and the preprocessor"),
    (id: "types", num: 3, title: "the type system"),
    (id: "pointers", num: 4, title: "pointers, arrays, and memory"),
    (id: "machine", num: 5, title: "the abstract machine and undefined behavior"),
    (id: "stdlib", num: 6, title: "the c23 library"),
    (id: "llvm", num: 7, title: "llvm: the architecture of the toolchain"),
    (id: "ir", num: 8, title: "reading llvm ir"),
    (id: "opt", num: 9, title: "optimization: what -O actually does"),
    (id: "tooling", num: 10, title: "clang tooling and diagnostics"),
    (id: "processes", num: 11, title: "processes and program lifecycle"),
    (id: "virtualmemory", num: 12, title: "virtual memory and paging"),
    (id: "caches", num: 13, title: "caches and locality"),
    (id: "heap", num: 14, title: "the heap and allocators"),
    (id: "threads", num: 15, title: "threads and synchronization"),
    (id: "atomics", num: 16, title: "atomics and memory ordering"),
    (id: "scheduling", num: 17, title: "cpu scheduling algorithms"),
    (id: "async", num: 18, title: "asynchronous patterns in c"),
    (id: "allocators", num: 19, title: "allocator designs"),
    (id: "measurement", num: 20, title: "measurement, profiling, and p99"),
    (id: "capstone", num: 21, title: "capstone: particle kernel and row cruncher"),
    (id: "cloudmodel", num: 22, title: "the cloud model"),
    (id: "terraform", num: 23, title: "terraform: language and core workflow"),
    (id: "modules", num: 24, title: "terraform modules and workflows"),
    (id: "aws", num: 25, title: "aws essentials through terraform"),
    (id: "gcp", num: 26, title: "gcp essentials through terraform"),
    (id: "multicloud", num: 27, title: "multi-cloud practice"),
    (id: "http-kernel", num: 28, title: "http kernel"),
    (id: "middleware", num: 29, title: "middleware"),
    (id: "users", num: 30, title: "the user resource"),
    (id: "authn", num: 31, title: "authn"),
    (id: "authz", num: 32, title: "authz and rbac"),
    (id: "store", num: 33, title: "store"),
    (id: "conc", num: 34, title: "concurrency control"),
    (id: "cache", num: 35, title: "caching"),
    (id: "limit", num: 36, title: "rate limiting"),
    (id: "obs", num: 37, title: "observability"),
    (id: "load", num: 38, title: "load and p99"),
    (id: "ship", num: 39, title: "ship it"),
    (id: "suite", num: 40, title: "the test suite"),
    (id: "appendices", num: 41, title: "appendices: topic matrix and sources"),
  ),
)
