// book 16 manifest: chapter registry used by cross references and stubs
#let repertoire = (
  num: 16,
  volume: false,
  title: "the interview repertoire",
  meta: (
    title: "the interview repertoire",
    subtitle: "working answers for frequent questions",
    author: "Raeliosol",
    version: "5.0",
    volume-label: "book 16",
  ),
  chapters: (
    (id: "landscape", num: 1, title: "the 2026 interview landscape"),
    (id: "paradigms", num: 2, title: "paradigms: oop, fp, mvc, mvvm, ecs"),
    (id: "datastructures", num: 3, title: "data structures, implemented"),
    (id: "graphs", num: 4, title: "graphs: dfs, bfs, topological sort"),
    (id: "classics1", num: 5, title: "classics part 1: warmup, arrays, hashing"),
    (id: "classics2", num: 6, title: "classics part 2: dynamic programming and tries"),
    (id: "js-core", num: 7, title: "javascript core: scope, closures, event loop"),
    (id: "js-dom", num: 8, title: "javascript and the dom"),
    (id: "js-fromscratch", num: 9, title: "javascript from scratch"),
    (id: "js-data", num: 10, title: "data plumbing: csv to mongodb"),
    (id: "react-core", num: 11, title: "react core: components, props, virtual dom"),
    (id: "react-hooks", num: 12, title: "react hooks and routing"),
    (id: "react-state", num: 13, title: "react state: context, redux, graphql"),
    (id: "react-build", num: 14, title: "react build: a listing page, test driven"),
    (id: "go-runtime", num: 15, title: "go runtime: scheduler, gc, patterns"),
    (id: "go-testing", num: 16, title: "go testing: mocks and dependency injection"),
    (id: "db-answers", num: 17, title: "database answers"),
    (id: "network-answers", num: 18, title: "network answers"),
    (id: "design-answers", num: 19, title: "system design answers"),
    (id: "go-build1", num: 20, title: "go build part 1: fetchers and rest apis"),
    (id: "go-build2", num: 21, title: "go build part 2: storefront and live features"),
    (id: "go-streaming", num: 22, title: "go streaming: jetstream batch pipelines"),
    (id: "algopatterns", num: 23, title: "algorithm patterns: window, pointers, search, greedy, bits"),
    (id: "weightedgraphs", num: 24, title: "weighted graphs: dijkstra, union-find, mst"),
    (id: "distributed-answers", num: 25, title: "distributed systems answers"),
    (id: "systems-answers", num: 26, title: "systems and runtime answers"),
    (id: "math-answers", num: 27, title: "mathematics answers"),
    (id: "mining-answers", num: 28, title: "data mining answers"),
    (id: "python-answers", num: 29, title: "python answers"),
    (id: "lua-answers", num: 30, title: "lua answers"),
    (id: "csharp-answers", num: 31, title: "c sharp answers"),
    (id: "css-answers", num: 32, title: "css answers: box model, cascade, layout"),
    (id: "rendering-answers", num: 33, title: "the rendering pipeline and accessibility"),
    (id: "security-answers", num: 34, title: "security answers: the named taxonomy"),
    (id: "estimation-answers", num: 35, title: "back of the envelope, said aloud"),
    (id: "design-prompts", num: 36, title: "system design prompts, four worked"),
    (id: "behavioral-answers", num: 37, title: "behavioral answers, from the register"),
    (id: "observed-answers", num: 38, title: "the observed round, take-homes, debugging"),
    (id: "negotiation-answers", num: 39, title: "offers and negotiation"),
    (id: "transfer-answers", num: 40, title: "the transfer answer: java and rust shops"),
    (id: "onebrc", num: 41, title: "the one billion row challenge"),
    (id: "appendices", num: 42, title: "appendices: question index and sources"),
  ),
)
