// book 14 manifest: chapter registry used by cross references and stubs
#let gamesystems = (
  num: 14,
  volume: false,
  title: "game systems and architecture",
  meta: (
    title: "game systems and architecture",
    subtitle: "an engineering handbook",
    author: "gabriel la",
    version: "3.0",
    volume-label: "book 14",
  ),
  chapters: (
    (id: "gameloop", num: 1, title: "the game loop and time"),
    (id: "ecstheory", num: 2, title: "ecs theory"),
    (id: "ecsimpl", num: 3, title: "an ecs implementation in c#"),
    (id: "dod", num: 4, title: "data oriented design"),
    (id: "fsm", num: 5, title: "finite state machines"),
    (id: "behavior", num: 6, title: "behavior trees and utility scoring"),
    (id: "math", num: 7, title: "deterministic math"),
    (id: "physics", num: 8, title: "physics"),
    (id: "terrain", num: 9, title: "terrain: heightmaps"),
    (id: "turns", num: 10, title: "turn systems and game flow"),
    (id: "randomness", num: 11, title: "randomness and determinism discipline"),
    (id: "serialization", num: 12, title: "serialization and save systems"),
    (id: "testing", num: 13, title: "testing games"),
    (id: "characters", num: 14, title: "characters and progression"),
    (id: "items", num: 15, title: "items, weapons, and crafting"),
    (id: "pets", num: 16, title: "pets and companions"),
    (id: "expeditions", num: 17, title: "expeditions and bosses"),
    (id: "scripting", num: 18, title: "embedded scripting: hosting lua"),
    (id: "capstone1", num: 19, title: "capstone part 1: the battle engine"),
    (id: "capstone2", num: 20, title: "capstone part 2: the campaign core"),
    (id: "capstone3", num: 21, title: "capstone part 3: the playable mvp"),
    (id: "capstone4", num: 22, title: "capstone part 4: balance by simulation"),
    (id: "appendices", num: 23, title: "appendices: topic matrix and sources"),
  ),
)
