// book 4 manifest: chapter registry used by cross references and stubs
#let javabook = (
  num: 4,
  volume: false,
  title: "java 27",
  meta: (
    title: "java 27",
    subtitle: "a complete language manual",
    author: "Mr. Raheliosol",
    version: "1.0",
    volume-label: "book 4",
  ),
  chapters: (
    (id: "toolchain", num: 1, title: "toolchain and the jdk"),
    (id: "ladder", num: 2, title: "from java 8 to java 27"),
    (id: "lexical", num: 3, title: "lexical structure"),
    (id: "types", num: 4, title: "types and values"),
    (id: "classes", num: 5, title: "classes and objects"),
    (id: "generics", num: 6, title: "generics"),
    (id: "enums", num: 7, title: "enums, annotations, and nested types"),
    (id: "functional", num: 8, title: "functional java"),
    (id: "patterns", num: 9, title: "pattern matching"),
    (id: "concurrency", num: 10, title: "concurrency: threads to virtual threads"),
    (id: "runtime", num: 11, title: "memory and runtime"),
    (id: "collections", num: 12, title: "collections and streams"),
    (id: "formats", num: 13, title: "text, numbers, and time"),
    (id: "io", num: 14, title: "io and networking"),
    (id: "modules", num: 15, title: "modules and jlink"),
    (id: "reflection", num: 16, title: "reflection and method handles"),
    (id: "security", num: 17, title: "security and cryptography"),
    (id: "testing", num: 18, title: "testing and idioms"),
    (id: "httpkernel", num: 19, title: "http kernel"),
    (id: "middleware", num: 20, title: "middleware"),
    (id: "users", num: 21, title: "the user resource"),
    (id: "authn", num: 22, title: "authn"),
    (id: "authz", num: 23, title: "authz and rbac"),
    (id: "store", num: 24, title: "store"),
    (id: "conc", num: 25, title: "concurrency control"),
    (id: "cache", num: 26, title: "caching"),
    (id: "limit", num: 27, title: "rate limiting"),
    (id: "obs", num: 28, title: "observability"),
    (id: "load", num: 29, title: "load and p99"),
    (id: "shipit", num: 30, title: "ship it"),
    (id: "suite", num: 31, title: "the test suite"),
    (id: "capstone", num: 32, title: "capstone: line clone chat with mini apps"),
    (id: "appendices", num: 33, title: "appendices: coverage and sources"),
  ),
)
