// book 3 manifest: chapter registry used by cross references and stubs
#let gobook = (
  num: 3,
  volume: false,
  title: "go 1.27",
  meta: (
    title: "go 1.27",
    subtitle: "a complete language manual",
    author: "gabriel la",
    version: "7.0",
    volume-label: "book 3",
  ),
  chapters: (
    (id: "toolchain", num: 1, title: "toolchain and modules"),
    (id: "lexical", num: 2, title: "lexical structure"),
    (id: "types", num: 3, title: "types"),
    (id: "generics", num: 4, title: "generics and generic methods"),
    (id: "functions", num: 5, title: "functions"),
    (id: "concurrency", num: 6, title: "concurrency"),
    (id: "errors", num: 7, title: "error handling"),
    (id: "structure", num: 8, title: "program structure"),
    (id: "runtime", num: 9, title: "runtime"),
    (id: "allocation", num: 10, title: "allocation: mspans, size classes, escape analysis, sync.Pool"),
    (id: "profiling", num: 11, title: "profiling: pprof, the tracer, benchstat, p99"),
    (id: "stdlib1", num: 12, title: "stdlib tour 1: fmt, errors, slices, maps, cmp, time, slog"),
    (id: "stdlib2", num: 13, title: "stdlib tour 2: json/v2, uuid, net/http, crypto, simd, os, io, testing"),
    (id: "testing", num: 14, title: "testing"),
    (id: "idioms", num: 15, title: "idioms"),
    (id: "htmx", num: 16, title: "htmx 4: html over the wire"),
    (id: "templ", num: 17, title: "templ: compiled html components"),
    (id: "httpkernel", num: 18, title: "http kernel"),
    (id: "middleware", num: 19, title: "middleware"),
    (id: "users", num: 20, title: "the user resource"),
    (id: "authn", num: 21, title: "authn"),
    (id: "authz", num: 22, title: "authz and rbac"),
    (id: "store", num: 23, title: "store"),
    (id: "conc", num: 24, title: "concurrency control"),
    (id: "cache", num: 25, title: "caching"),
    (id: "limit", num: 26, title: "rate limiting"),
    (id: "obs", num: 27, title: "observability"),
    (id: "load", num: 28, title: "load and p99"),
    (id: "shipit", num: 29, title: "ship it"),
    (id: "suite", num: 30, title: "the test suite"),
    (id: "numstats", num: 31, title: "numerical statistics in go"),
    (id: "fitting", num: 32, title: "fitting, backtesting, and guarded promotion"),
    (id: "enginetwin", num: 33, title: "the offline engine and its js twin"),
    (id: "capstone", num: 34, title: "capstone: concurrent crawler, indexer, and web ui"),
    (id: "appendices", num: 35, title: "appendices: coverage and sources"),
  ),
)
