// book 2 manifest: chapter registry used by cross references and stubs
#let mathbook = (
  num: 2,
  volume: false,
  title: "mathematics for programmers",
  meta: (
    title: "mathematics for programmers",
    subtitle: "trigonometry to monads in c23, with a physics game capstone",
    author: "gabriel la",
    version: "2.0",
    volume-label: "book 2",
  ),
  chapters: (
    (id: "float", num: 1, title: "floating point anatomy"),
    (id: "error", num: 2, title: "error, conditioning, and stability"),
    (id: "trig", num: 3, title: "trigonometry"),
    (id: "coordgeo", num: 4, title: "coordinate geometry"),
    (id: "vectors", num: 5, title: "vectors and vector spaces"),
    (id: "matrices", num: 6, title: "matrices and linear systems"),
    (id: "inner", num: 7, title: "inner products and projections"),
    (id: "decomp", num: 8, title: "matrix decompositions"),
    (id: "univariate", num: 9, title: "single-variable calculus"),
    (id: "multivariate", num: 10, title: "multivariate calculus"),
    (id: "optimization", num: 11, title: "continuous optimization"),
    (id: "autodiff", num: 12, title: "automatic differentiation"),
    (id: "proof", num: 13, title: "logic, sets, and proof"),
    (id: "combinatorics", num: 14, title: "combinatorics"),
    (id: "graphs", num: 15, title: "graphs and order theory"),
    (id: "groups", num: 16, title: "groups and subgroups"),
    (id: "actions", num: 17, title: "group actions and structure"),
    (id: "probability", num: 18, title: "probability and distributions"),
    (id: "statistics", num: 19, title: "statistics and inference"),
    (id: "roots", num: 20, title: "root finding"),
    (id: "interp", num: 21, title: "interpolation and approximation"),
    (id: "quadrature", num: 22, title: "quadrature and differential equations"),
    (id: "iterative", num: 23, title: "iterative methods and conditioning"),
    (id: "strategic", num: 24, title: "strategic games"),
    (id: "sequential", num: 25, title: "sequential and repeated games"),
    (id: "adt", num: 26, title: "algebraic data types in c23"),
    (id: "railway", num: 27, title: "option, result, and the railway"),
    (id: "monads", num: 28, title: "functors and monads in c"),
    (id: "pipeline", num: 29, title: "pipelines and effects"),
    (id: "capstone-design", num: 30, title: "capstone: the arena game, design"),
    (id: "capstone-impl", num: 31, title: "capstone: the arena game, implementation"),
    (id: "capstone-verify", num: 32, title: "capstone: the arena game, verification"),
    (id: "appendices", num: 33, title: "appendices: coverage and sources"),
  ),
)
