#import "../../theme/lib.typ": listing, snippet, callout, diagram, cdraw, xref-to

= group actions and structure

Chapter 16 built the nouns: group, order, subgroup, cyclic generator, cosets, Lagrange. This chapter builds the verbs that compare and combine them: homomorphisms and isomorphisms as table-preserving maps, quotients that turn coset partitions into arithmetic, direct products with their lcm order law, rings and fields where a second operation joins, finite fields built from polynomials over $Z_2$, the dihedral group $D_4$ acting on a square, Burnside's orbit count on colorings, and a toy Diffie-Hellman exchange whose secrecy is exactly the discrete logarithm. Every behavioral claim below is one of the 61 checks in the 4 samples of chapter 17 or a sentence quoted from a canonical source fetched 2026-09-21. Where #xref-to("dsa", "numtheory") and #xref-to("dsa", "numtheory2") run modular exponentiation, discrete logs, and Burnside counting as algorithms, this chapter is the structure underneath.

== homomorphisms and isomorphisms

Definition first. A homomorphism $phi : G -> H$ is a map with $phi(a dot b) = phi(a) dot phi(b)$ for all $a, b in G$: products map to products, so the whole table of $G$ lands in the table of $H$. An isomorphism is a bijective homomorphism, and two groups are isomorphic when one exists, written $G ~= H$: same table, different labels. The kernel, $"ker" phi = {g in G : phi(g) = e_H}$, measures how far $phi$ sits from injective.

The pinned fixture is the parity map $phi : Z_4 -> Z_2$, $phi(k) = k mod 2$. It preserves all 16 pairs, its image is all of $Z_2$, and its kernel is ${0, 2}$, which closes under addition mod 4 on its own: $0 + 2 = 2$, $2 + 2 = 0$. A kernel is never an accident, it is always a subgroup, and chapter 2's error vocabulary returns here: the kernel is the null space of the map.

The dry run: same order 4, two different groups, told apart by counting orders.

+ In $Z_4$ the orders of $0, 1, 2, 3$ are $1, 4, 2, 4$: two elements of order 4.
+ In $Z_2 times Z_2$ every element satisfies $a dot a = e$, so the orders are $1, 2, 2, 2$: no element of order 4.
+ Order is preserved by any isomorphism, since $phi(a)^k = phi(a^k)$, so no bijection can carry one census onto the other: $Z_4$ is not isomorphic to $Z_2 times Z_2$.

The same census tool reads the unit groups. $U(8) = {1, 3, 5, 7}$ has orders $1, 2, 2, 2$, the Klein four group again. $U(10) = {1, 3, 7, 9}$ has orders $1, 4, 4, 2$: cyclic, generated by 3. So $U(8)$ and $U(10)$ are not isomorphic despite both having order 4. But $U(12) = {1, 5, 7, 11}$ has orders $1, 2, 2, 2$, and the explicit map $1 -> 1$, $3 -> 5$, $5 -> 7$, $7 -> 11$ preserves all 16 products of $U(8)$: $U(8) ~= U(12)$, witnessed rather than suggested.

#table(
  columns: (auto, auto, auto, auto),
  inset: 4pt,
  table.header([*group*], [*order*], [*order census*], [*verdict*]),
  [$Z_4$], [4], [1, 4, 2, 4], [cyclic],
  [$Z_2 times Z_2$], [4], [1, 2, 2, 2], [klein],
  [$U(8)$], [4], [1, 2, 2, 2], [klein],
  [$U(10)$], [4], [1, 4, 4, 2], [cyclic],
  [$U(12)$], [4], [1, 2, 2, 2], [klein],
)

#listing("math/samples/src/Ch17/hom.c", first: 122, last: 145, caption: [hom.c, both kernels pinned as bitmasks, and the kernel {0,2} closing into a subgroup of z4 on its own])

#listing("math/samples/src/Ch17/hom.c", first: 170, last: 200, caption: [hom.c, the three order censuses and the witnessed isomorphism u(8) -> u(12): every product maps to the paired product, so the tables are the same table])

#callout("pitfall", "a matching census is evidence, not a certificate", [
  equal order counts for every order do not force an isomorphism in general: the census is a cheap invariant that separates groups, not a complete one. for groups of order 4 it happens to decide everything, because only two group structures of order 4 exist, and the census tells them apart. the honest certificate is always a map: check all $n^2$ products like the u(8) -> u(12) witness above, checks 10 and 11 of hom.c.
])

#diagram([the parity map collapses z4 onto z2 with kernel {0,2}, while the order census separates z4 from z2 x z2 with no map at all], length: 13pt, {
  let cell(x, y, w, t, dark) = {
    cdraw.rect((x - w / 2, y - 0.4), (x + w / 2, y + 0.4), fill: if dark { luma(205) } else { luma(245) }, radius: 0.02, stroke: luma(100))
    cdraw.content((x, y), t, size: 6pt)
  }
  cell(2.2, 6.8, 1.7, [0  ord 1], true)
  cell(2.2, 5.7, 1.7, [1  ord 4], false)
  cell(2.2, 4.6, 1.7, [2  ord 2], true)
  cell(2.2, 3.5, 1.7, [3  ord 4], false)
  cell(7.0, 5.8, 1.3, [0], true)
  cell(7.0, 4.3, 1.3, [1], false)
  cdraw.content((4.6, 7.7), [phi: k -> k mod 2], size: 6.5pt)
  cdraw.line((3.05, 6.8), (6.3, 5.95), stroke: luma(60), mark: (end: ">"))
  cdraw.line((3.05, 4.6), (6.3, 5.5), stroke: luma(60), mark: (end: ">"))
  cdraw.line((3.05, 5.7), (6.3, 4.5), stroke: luma(60), mark: (end: ">"))
  cdraw.line((3.05, 3.5), (6.3, 4.05), stroke: luma(60), mark: (end: ">"))
  cdraw.content((4.6, 2.5), [kernel = {0, 2}: both land on 0], size: 6pt)
  cdraw.content((11.4, 6.6), [z2 x z2 census], size: 6.5pt)
  cdraw.content((11.4, 5.9), [orders 1, 2, 2, 2], size: 6pt)
  cdraw.content((11.4, 5.2), [no element of order 4], size: 6pt)
  cdraw.content((11.4, 4.5), [so no isomorphism from z4], size: 6pt)
})

== cosets and quotients

Lagrange's partition from chapter 16 says the cosets of a subgroup $H$ tile $G$ into equal blocks. A quotient asks when the blocks themselves form a group under $(a H) dot (b H) = (a b) H$: exactly when left and right cosets agree, $g H = H g$ for every $g$, the normal subgroups (Wikipedia, "quotient group", fetched 2026-09-21: "A subgroup N of a group G is normal if and only if the coset equality aN = Na holds for all a in G").

The dry run: two subgroups of the abelian $Z_6$, where normality is free, one subgroup of $S_3$ where it fails.

+ $H = {0, 2, 4}$ tiles $Z_6$ into $H$ and $1 + H = {1, 3, 5}$. Adding blocks: $(1+H) + (1+H) = 2 + H = H$, a two-element group, isomorphic to $Z_2$. Every one of the 9 representative pairs lands in the same block, so the block sum does not depend on representatives.
+ $H = {0, 3}$ tiles $Z_6$ into ${0, 3}, {1, 4}, {2, 5}$, and three copies of $1 + H$ return to $H$: the quotient adds like $Z_3$.
+ In $S_3$ with $H = {e, "s01"}$: the left coset $r H = {r, "s02"}$ while the right coset $H r = {r, "s12"}$. Different sets, so $H$ is not normal.

The failure has a product witness, worth seeing once in full. Multiply the cosets $r H$ and $r^2 H$ elementwise: the four products $r dot r^2$, $r dot "s12"$, $"s02" dot r^2$, $"s02" dot "s12"$ are $e, "s01", "s12", r^2$, which sit in two different cosets at once, ${e, "s01"}$ and ${r^2, "s12"}$. The result is not a coset, so the candidate operation has no value: coset arithmetic on a non-normal subgroup is not merely inconvenient, it is undefined.

The repair inside $S_3$: the rotations $A_3 = {e, r, r^2}$ do satisfy $g A_3 = A_3 g$ for all six $g$, checks 11 and 12 of quotients.c, and the quotient works. The even permutations form one coset, the three reflections the other, and every odd times odd product is even on all 9 pairs: $S_3 \/ A_3$ is a group of order 2, isomorphic to $Z_2$, the sign homomorphism's kernel doing what section 1 promised.

#listing("math/samples/src/Ch17/quotients.c", first: 111, last: 130, caption: [quotients.c, the quotient table check: (1+H)+(1+H) = 2+H = H gives z2, and the {0,3} blocks tile z6 three ways])

#listing("math/samples/src/Ch17/quotients.c", first: 158, last: 179, caption: [quotients.c, the non-normal witness in s3: rh = {r, s02} against hr = {r, s12}, then the elementwise coset product landing in two cosets at once])

#callout("note", "abelian groups divide freely", [
  in an abelian group $g h = h g$ holds before you ask, so $g H = H g$ automatically: every subgroup of every abelian group is normal, and quotients are always available. that is why $Z_6$ produced two clean quotients above while $S_3$, the smallest non-abelian group, needed the scan. checks 10 through 12 of quotients.c run that scan for you.
])

#diagram([z6 as a ring of 6 residues: opposite pairs form the three cosets of {0,3}, shaded dark, medium, light, and they add like z3], length: 13pt, {
  let node(x, y, t, fill) = {
    cdraw.circle((x, y), radius: 0.42, fill: fill, stroke: luma(60))
    cdraw.content((x, y), t, size: 6.5pt)
  }
  node(6.4, 6.45, [0], luma(205))
  node(8.0, 5.53, [1], luma(225))
  node(8.0, 3.67, [2], luma(245))
  node(6.4, 2.75, [3], luma(205))
  node(4.8, 3.67, [4], luma(225))
  node(4.8, 5.53, [5], luma(245))
  cdraw.line((6.75, 6.25), (7.65, 5.72), stroke: luma(100), mark: (end: ">"))
  cdraw.line((8.0, 5.0), (8.0, 4.2), stroke: luma(100), mark: (end: ">"))
  cdraw.line((7.65, 3.48), (6.75, 2.95), stroke: luma(100), mark: (end: ">"))
  cdraw.line((6.05, 2.95), (5.15, 3.48), stroke: luma(100), mark: (end: ">"))
  cdraw.line((4.8, 4.2), (4.8, 5.0), stroke: luma(100), mark: (end: ">"))
  cdraw.line((5.15, 5.72), (6.05, 6.25), stroke: luma(100), mark: (end: ">"))
  let sw(x, fill, lab) = {
    cdraw.circle((x, 0.9), radius: 0.3, fill: fill, stroke: luma(100))
    cdraw.content((x + 1.5, 0.9), lab, size: 6pt)
  }
  sw(1.2, luma(205), [C0 = {0, 3}])
  sw(5.2, luma(225), [C1 = {1, 4}])
  sw(9.2, luma(245), [C2 = {2, 5}])
  cdraw.content((6.4, -0.3), [C1 + C1 = C2, and three copies of C1 make C0], size: 6.5pt)
})

== direct products

Two groups combine without interacting: the direct product $G times H$ pairs elements and multiplies componentwise, $(a, b) dot (a', b') = (a dot a', b dot b')$. The order law is the whole section: $"ord"(a, b) = "lcm"("ord" a, "ord" b)$, because $(a, b)^k = (a^k, b^k)$ returns to the identity exactly when both components do.

The dry run: $Z_4 times Z_6$ has 24 elements, and the pair $(1 mod 4, 1 mod 6)$ has order $"lcm"(4, 6) = 12$, double the largest order inside either factor. The lazy pair $(2, 3)$ dies in $"lcm"(2, 2) = 2$ steps. The lcm law itself is checked on all 24 elements, not asserted.

The law also separates products from cyclic groups. $Z_2 times Z_4$ has $2 dot 4 = 8$ elements but maximum element order $"lcm"(2, 4) = 4$, so it cannot be $Z_8$, which has an element of order 8. Whereas $Z_3 times Z_4$ is $Z_12$ in disguise: the map $(a, b) -> 4a + 9b mod 12$ hits every residue exactly once and preserves addition on all 144 pairs, with $4 equiv (1, 0)$ and $9 equiv (0, 1)$ encoding each component. That is the Chinese remainder theorem as a table scan.

#listing("math/samples/src/Ch17/hom.c", first: 86, last: 108, caption: [hom.c, the product element as a two-field struct with compound literals, added componentwise, its order walked to the identity, lcm on hand])

#listing("math/samples/src/Ch17/hom.c", first: 211, last: 225, caption: [hom.c, the lcm order law pinned on pairs then scanned on all 24 elements of z4 x z6])

#diagram([the crt grid: each cell of z3 x z4 labeled by its image 4a + 9b mod 12, the 12 residues appearing exactly once], length: 13pt, {
  let cell(x, y, w, h, t, dark) = {
    cdraw.rect((x, y), (x + w, y + h), fill: if dark { luma(235) } else { luma(245) }, radius: 0.02, stroke: luma(100))
    cdraw.content((x + w / 2, y + h / 2), t, size: 6.5pt)
  }
  cdraw.content((0.6, 6.6), [b=3], size: 6pt)
  cdraw.content((0.6, 5.3), [b=2], size: 6pt)
  cdraw.content((0.6, 4.0), [b=1], size: 6pt)
  cdraw.content((0.6, 2.7), [b=0], size: 6pt)
  cell(1.6, 6.0, 2.6, 1.1, [3], false)
  cell(1.6, 4.7, 2.6, 1.1, [6], false)
  cell(1.6, 3.4, 2.6, 1.1, [9], false)
  cell(1.6, 2.1, 2.6, 1.1, [0], true)
  cell(4.6, 6.0, 2.6, 1.1, [7], false)
  cell(4.6, 4.7, 2.6, 1.1, [10], false)
  cell(4.6, 3.4, 2.6, 1.1, [1], false)
  cell(4.6, 2.1, 2.6, 1.1, [4], true)
  cell(7.6, 6.0, 2.6, 1.1, [11], false)
  cell(7.6, 4.7, 2.6, 1.1, [2], false)
  cell(7.6, 3.4, 2.6, 1.1, [5], false)
  cell(7.6, 2.1, 2.6, 1.1, [8], true)
  cdraw.content((2.9, 7.6), [a=0], size: 6pt)
  cdraw.content((5.9, 7.6), [a=1], size: 6pt)
  cdraw.content((8.9, 7.6), [a=2], size: 6pt)
  cdraw.content((5.4, 0.9), [column a contributes 4a, row b contributes 9b], size: 6pt)
  cdraw.content((5.4, 1.6), [the b=0 row reads 0, 4, 8 across a], size: 6pt)
})

== rings and fields

A ring adds a second operation to a group. Definition: $(R, +, dot)$ is a ring when $R$ is an abelian group under $+$, multiplication is associative with an identity (for rings with 1), and distributivity $a dot (b + c) = a dot b + a dot c$ ties them together. A field is a commutative ring where every nonzero element has a multiplicative inverse.

The integers mod $n$ are the fixture ring, and the two operations disagree about $n$ in exactly one way. Under addition $Z_n$ is always a group. Under multiplication it is a field precisely when $n$ is prime, and the reason is the zero divisors: in $Z_6$, $2 dot 3 = 6 equiv 0$, and a zero divisor can never invert, because $x dot 2 equiv 1$ would give $3 dot x dot 2 equiv 3 dot 1 equiv 3$ on one side and $3 dot 0 equiv 0$ on the other.

The dry run: $Z_5$ inverts everything, $1 dot 1 = 1$, $2 dot 3 = 6 equiv 1$, $4 dot 4 = 16 equiv 1$. $Z_6$ keeps only 1 and 5, and the $Z_12$ census separates the rest: zero divisors $2, 3, 4, 6, 8, 9, 10$ against units $1, 5, 7, 11$, with $5 dot 5 = 25 equiv 1$, check 4 of fields.c. The scan over $n = 2$ to 12 pins the equivalence both directions, primes 2, 3, 5, 7, 11 have all nonzero residues invertible, every composite has a zero divisor pair, and distributivity holds on all 216 triples of $Z_6$, the hand triple $2 dot (3 + 5) = 16 equiv 4$ against $6 + 10 equiv 4$ among them.

#table(
  columns: (auto, auto, auto, auto),
  inset: 4pt,
  table.header([*ring*], [*zero divisors*], [*units*], [*field*]),
  [$Z_5$], [none], [1, 2, 3, 4], [yes],
  [$Z_6$], [2, 3, 4], [1, 5], [no],
  [$Z_8$], [2, 4, 6], [1, 3, 5, 7], [no],
  [$Z_12$], [2, 3, 4, 6, 8, 9, 10], [1, 5, 7, 11], [no],
)

#listing("math/samples/src/Ch17/fields.c", first: 82, last: 113, caption: [fields.c, the inverse scan in z5, the zero divisors of z6, and the prime-versus-composite equivalence scanned for every n from 2 to 12])

#callout("note", "u(n) is the field question with the zeros kept", [
  chapter 16 met $U(n)$ as the units mod $n$, a group of order $phi(n)$. the field scan rephrases it: $Z_n$ is a field exactly when the units are everything but zero, $phi(n) = n - 1$, which holds exactly for primes. the group of chapter 16 and the ring of this chapter meet on the same residue set, and checks 1 through 4 of fields.c walk the equivalence end to end.
])

#diagram([the containment ladder from ring to field: z6 dies at zero divisors, z survives them but keeps only 1 and -1 invertible, z5 and gf(4) arrive at the field rung], length: 13pt, {
  let rung(y, t, lvl) = {
    cdraw.rect((2.0, y), (9.0, y + 1.0), fill: luma(235 + lvl * 5), radius: 0.02, stroke: luma(100))
    cdraw.content((5.5, y + 0.5), t, size: 6pt)
  }
  rung(6.6, [ring: + abelian, dot monoid], 0)
  rung(5.0, [commutative ring with 1], 1)
  rung(3.4, [integral domain: no zero divisors], 2)
  rung(1.8, [field: every nonzero a unit], 3)
  cdraw.line((8.2, 6.6), (8.2, 6.0), stroke: luma(60), mark: (end: ">"))
  cdraw.line((8.2, 5.0), (8.2, 4.4), stroke: luma(60), mark: (end: ">"))
  cdraw.line((8.2, 3.4), (8.2, 2.8), stroke: luma(60), mark: (end: ">"))
  let ex(y, t) = {
    cdraw.rect((10.0, y), (13.8, y + 0.8), fill: luma(245), radius: 0.02, stroke: (paint: luma(150), dash: "dashed"))
    cdraw.content((11.9, y + 0.4), t, size: 6pt)
  }
  ex(6.7, [M_2(Z) matrices])
  ex(5.1, [Z_6, Z_10])
  ex(3.5, [Z: 1,-1 units])
  ex(1.9, [Z_5, GF(4)])
  cdraw.line((9.0, 7.1), (10.0, 7.1), stroke: luma(150))
  cdraw.line((9.0, 5.5), (10.0, 5.5), stroke: luma(150))
  cdraw.line((9.0, 3.9), (10.0, 3.9), stroke: luma(150))
  cdraw.line((9.0, 2.3), (10.0, 2.3), stroke: luma(150))
})

== finite fields

There is no $Z_4$-style field of order 4, since 4 is composite, yet a field of four elements exists: build it from polynomials. Over $Z_2$, take the polynomials of degree below 2, which are exactly $0, 1, x, x + 1$, and reduce products modulo $x^2 + x + 1$. Since $x^2 equiv x + 1$ over $Z_2$ (the minus signs vanish), multiplication closes on the four elements: $(x + 1)^2 = x^2 + 2x + 1 = x^2 + 1 equiv x$, and the full table is pinned below. This is $"GF"(4) = Z_2[x] \/ (x^2 + x + 1)$, and $x^2 + x + 1$ being irreducible over $Z_2$ plays the role the prime $p$ played for $Z_p$.

The dry run: powers of $x$ in $"GF"(4)$.

+ $x dot x = x^2 equiv x + 1$.
+ $x dot (x + 1) = x^2 + x equiv (x + 1) + x = 1$: so $x^3 = 1$.
+ The nonzero ladder is $x, x + 1, 1$, orders $1, 3, 3$: the multiplicative group is cyclic of order 3, generated by $x$.

One dimension up, $"GF"(8) = Z_2[x] \/ (x^3 + x + 1)$ on the eight polynomials of degree below 3. The reduction rule $x^3 equiv x + 1$ chains into $x^4 equiv x^2 + x$, and the powers of $x$ walk the entire nonzero field: $x, x^2, x + 1, x^2 + x, x^2 + x + 1, x^2 + 1, 1$, seven values, all distinct, returning to $x$. Since 7 is prime, every element besides 1 has order 7. This is the general shape: the nonzero elements of a finite field form a multiplicative group, and that group is cyclic (Wikipedia, "finite field", fetched 2026-09-21: "The non-zero elements of a finite field form a multiplicative group" and "The structure theorem of finite abelian groups implies that this multiplicative group is cyclic, that is, all non-zero elements are powers of a single element"). The identity $a^q = a$ holds for every element of $"GF"(q)$, pinned in both fields at once.

#table(
  columns: (auto, auto, auto, auto, auto),
  inset: 4pt,
  table.header([*dot*], [0], [1], [x], [x+1]),
  [0], [0], [0], [0], [0],
  [1], [0], [1], [x], [x+1],
  [$x$], [0], [$x$], [$x+1$], [1],
  [$x+1$], [0], [$x+1$], [1], [$x$],
)

#listing("math/samples/src/Ch17/fields.c", first: 129, last: 147, caption: [fields.c, the pinned gf(4) multiplication table with the (x+1)^2 = x reduction on top])

#listing("math/samples/src/Ch17/fields.c", first: 168, last: 197, caption: [fields.c, gf(8) one dimension up: the x^3 = x+1 rule pinned, the seven powers of x walking every nonzero element home, so every non-identity element has order 7])

#diagram([the multiplicative group of gf(4) is a 3-cycle: multiplying by x walks x, x+1, 1 and closes], length: 13pt, {
  let node(x, y, t, dark) = {
    cdraw.circle((x, y), radius: 0.5, fill: if dark { luma(205) } else { luma(245) }, stroke: luma(60))
    cdraw.content((x, y), t, size: 6.5pt)
  }
  node(4.0, 3.6, [x], true)
  node(6.8, 6.0, [x+1], false)
  node(6.8, 1.2, [1], false)
  cdraw.line((4.4, 3.95), (6.35, 5.6), stroke: luma(60), mark: (end: ">"))
  cdraw.line((6.8, 5.5), (6.8, 1.75), stroke: luma(60), mark: (end: ">"))
  cdraw.line((6.35, 1.55), (4.4, 3.25), stroke: luma(60), mark: (end: ">"))
  cdraw.content((3.0, 5.6), [x dot x = x+1], size: 6pt)
  cdraw.content((9.6, 3.6), [x dot (x+1) = 1], size: 6pt)
  cdraw.content((3.0, 1.0), [x dot 1 = x], size: 6pt)
  cdraw.content((5.4, -0.4), [gf(4)* has order 3, gf(8)* has order 7], size: 6.5pt)
  cdraw.content((5.4, -1.1), [one generator covers every nonzero element], size: 6pt)
})

== the dihedral group d4 acts on a square

The symmetries of the square form $D_4$: four rotations, four reflections, each a permutation of the four vertices. With $r$ the quarter turn and $s$ the reflection fixing vertices 0 and 2, every element is one of $e, r, r^2, r^3, s, r s, r^2 s, r^3 s$, and two relations pin the whole group: $r^4 = s^2 = e$ and $s ∘ r = r^3 ∘ s$, pass an $s$ left across an $r$ and the $r$ inverts. That exchange rule is the non-commutativity in one line, and it is why the 64 products close without storing a table.

A group action is a group behaving like a machine on a set: each $g in G$ moves points $x -> g dot x$, with $e dot x = x$ and $g dot (h dot x) = (g ∘ h) dot x$. Two sets fall out. The orbit of $x$ is everything reachable, ${g dot x : g in G}$. The stabilizer of $x$ is everything that fixes it, ${g : g dot x = x}$, itself a subgroup.

The dry run: under the eight symmetries the orbit of vertex 0 is all 4 vertices, its stabilizer is exactly ${e, s}$, and $4 dot 2 = 8 = |D_4|$. That product is no coincidence, it is the orbit-stabilizer theorem, Lagrange counting twice: the cosets of the stabilizer biject with the orbit.

#table(
  columns: (auto, auto, auto, auto, auto, auto),
  inset: 4pt,
  table.header([*element*], [e], [r], [$r^2$], [s], [rs]),
  [order], [1], [4], [2], [2], [2],
  [fixes vertex 0], [yes], [no], [no], [yes], [no],
)

#listing("math/samples/src/Ch17/actions.c", first: 26, last: 42, caption: [actions.c, d4 as eight vertex permutations in a constexpr table, composition as one line])

#listing("math/samples/src/Ch17/actions.c", first: 147, last: 166, caption: [actions.c, the action read directly off the table: orbit of vertex 0 is all four vertices, stabilizer is {e, s}, product 8])

#diagram([the square under its own symmetry: r cycles the vertices, s holds 0 and 2 fixed across the diagonal], length: 13pt, {
  let v(x, y, t) = {
    cdraw.circle((x, y), radius: 0.42, fill: luma(205), stroke: luma(60))
    cdraw.content((x, y), t, size: 6.5pt)
  }
  cdraw.line((4.05, 5.6), (6.35, 5.6), stroke: luma(100), mark: (end: ">"))
  cdraw.line((7.0, 4.95), (7.0, 2.65), stroke: luma(100), mark: (end: ">"))
  cdraw.line((6.35, 2.0), (4.05, 2.0), stroke: luma(100), mark: (end: ">"))
  cdraw.line((3.4, 2.65), (3.4, 4.95), stroke: luma(100), mark: (end: ">"))
  v(3.4, 5.6, [0])
  v(7.0, 5.6, [1])
  v(7.0, 2.0, [2])
  v(3.4, 2.0, [3])
  cdraw.circle((5.2, 3.8), radius: 1.1, stroke: (paint: luma(150), dash: "dashed"))
  // r as a clockwise tangent chase along the dashed circle, two segments
  // on the top-right arc where the s diagonal does not pass
  cdraw.line((5.20, 4.90), (5.49, 4.86), stroke: luma(60))
  cdraw.line((5.49, 4.86), (5.75, 4.75), stroke: luma(60), mark: (end: ">"))
  cdraw.content((5.2, 6.6), [r: 0 -> 1 -> 2 -> 3 -> 0], size: 6pt)
  cdraw.line((3.4, 5.6), (7.0, 2.0), stroke: (paint: luma(150), dash: "dashed"))
  cdraw.content((2.4, 1.2), [s: fixes 0 and 2, swaps 1 and 3], size: 6pt)
  cdraw.content((10.1, 4.9), [orbit of 0 = all 4 vertices], size: 6pt)
  cdraw.content((10.1, 4.2), [stabilizer = {e, s}, size 2], size: 6pt)
  cdraw.content((10.1, 3.5), [4 x 2 = 8 = |D_4|], size: 6pt)
})

== burnside's lemma counts orbits

Colorings breed: 4 vertices with 2 colors give 16 raw colorings of the square, but symmetries eat the differences, and what a puzzle or a game asset wants is the count of colorings up to symmetry. Burnside's lemma is the averaging trick that gets it (Wikipedia, "Burnside's lemma", fetched 2026-09-21: "the number of orbits ... is equal to the average number of points fixed by an element of G"). A coloring is fixed by $g$ exactly when it is constant on each cycle of $g$, so with $k$ colors a permutation with $c$ cycles fixes $k^c$ colorings, and the orbit count is the average of $k^c$ over the group.

The dry run: the square, then the cube.

+ Square, 2 colors under $D_4$: the identity has 4 cycles and fixes $2^4 = 16$, the rotations $r, r^3$ have 1 cycle and fix 2 each, $r^2$ and the two axis reflections have 2 cycles and fix 4 each, the two diagonal reflections have 3 cycles and fix 8 each. Sum $16 + 2 + 2 + 4 + 4 + 4 + 8 + 8 = 48$, average $48 \/ 8 = 6$ orbits. With 3 colors the same cycle data gives $168 \/ 8 = 21$.
+ Cube faces, 2 colors under the 24 rotations: the rotations fall into 5 cycle classes on faces, and the fixed counts $2^6, 2^3, 2^4, 2^3, 2^2$ weighted by $1, 6, 3, 6, 8$ sum to $240$, average $240 \/ 24 = 10$ distinct colorings out of 64 raw. With 3 colors: $1368 \/ 24 = 57$.
+ Necklace, 6 beads, 2 colors under rotation only: a rotation by $s$ has $"gcd"(6, s)$ cycles, so the sum is $64 + 2 + 4 + 8 + 4 + 2 = 84$, average $84 \/ 6 = 14$.

#table(
  columns: (auto, auto, auto, auto, auto),
  inset: 4pt,
  table.header([*cube rotation class*], [*count*], [*face cycle type*], [*cycles*], [*2-color fixed*]),
  [identity], [1], [$(1,1,1,1,1,1)$], [6], [64],
  [quarter turns], [6], [$(1,1,4)$], [3], [8],
  [half turns, face axes], [3], [$(1,1,2,2)$], [4], [16],
  [half turns, edge axes], [6], [$(2,2,2)$], [3], [8],
  [third turns, vertex axes], [8], [$(3,3)$], [2], [4],
)

The cube's 24 rotations are themselves generated in code by closing two quarter turns under composition, and two guards keep the closure honest: exactly 24 elements, and every element sends opposite faces to opposite faces, so the closure never wanders into the 48-element full octahedral group. The cycle-count arithmetic is the cycle index evaluated at $k^1, k^2, ...$, which is where Polya enumeration generalizes counting to inventory. The algorithmic side, gcd-class necklace sums and bracelet reflections, is #xref-to("dsa", "combinatorics") territory.

#listing("math/samples/src/Ch17/actions.c", first: 179, last: 222, caption: [actions.c, the 24 cube rotations grown by closing two quarter-turn generators, with the group-order and opposite-face guards])

#listing("math/samples/src/Ch17/actions.c", first: 235, last: 261, caption: [actions.c, the cube and necklace averages from cycle counts alone: 240/24 = 10, 1368/24 = 57, 84/6 = 14, 780/6 = 130])

#callout("verify", "count, then cross-check by enumeration", [
  the orbit counts above come from the fixed-point average, which is one theorem deep. a brute-force cross-check that floods each orbit by applying every group element lands the same numbers, and it is four lines of code on these sizes: for each of the $k^n$ colorings not yet seen, flood its orbit and add 1. playground/math-ch17/gen.py did exactly that before any of these sums were trusted, 6 for the square, 10 for the cube.
])

#diagram([the five cube rotation classes with their counts and fixed colorings, summing to 240 over 24 rotations], length: 13pt, {
  let bar(x, y, w, t, dark) = {
    cdraw.rect((x, y), (x + w, y + 1.0), fill: if dark { luma(205) } else { luma(235) }, radius: 0.02, stroke: luma(100))
    cdraw.content((x + w / 2, y + 0.5), t, size: 6pt)
  }
  bar(0.4, 6.4, 4.0, [identity x1], false)
  bar(0.4, 5.0, 4.0, [quarter turns x6], true)
  bar(0.4, 3.6, 4.0, [face half turns x3], false)
  bar(0.4, 2.2, 4.0, [edge half turns x6], true)
  bar(0.4, 0.8, 4.0, [vertex thirds x8], false)
  cdraw.content((6.3, 7.3), [cycles], size: 6pt)
  cdraw.content((6.3, 6.9), [6], size: 6pt)
  cdraw.content((6.3, 5.5), [3], size: 6pt)
  cdraw.content((6.3, 4.1), [4], size: 6pt)
  cdraw.content((6.3, 2.7), [3], size: 6pt)
  cdraw.content((6.3, 1.3), [2], size: 6pt)
  cdraw.content((8.8, 7.3), [fixed 2^c], size: 6pt)
  cdraw.content((8.8, 6.9), [64], size: 6pt)
  cdraw.content((8.8, 5.5), [8], size: 6pt)
  cdraw.content((8.8, 4.1), [16], size: 6pt)
  cdraw.content((8.8, 2.7), [8], size: 6pt)
  cdraw.content((8.8, 1.3), [4], size: 6pt)
  cdraw.content((11.6, 7.3), [class sum], size: 6pt)
  cdraw.content((11.6, 6.9), [64], size: 6pt)
  cdraw.content((11.6, 5.5), [48], size: 6pt)
  cdraw.content((11.6, 4.1), [48], size: 6pt)
  cdraw.content((11.6, 2.7), [48], size: 6pt)
  cdraw.content((11.6, 1.3), [32], size: 6pt)
  cdraw.content((11.6, 0.3), [240], size: 6.5pt)
  cdraw.content((8.8, 0.3), [avg 240/24], size: 6pt)
  cdraw.content((8.8, -0.4), [10 two-color cubes], size: 6pt)
})

== diffie-hellman and the discrete logarithm

Diffie-Hellman builds a shared secret over a public wire inside $U(p)$: agree publicly on a prime $p$ and a generator $g$ of $U(p)$, each picks a secret exponent, they exchange $g^("secret")$ publicly, and both raise what they receive to their own secret, landing on $g^(a b)$ together (Wikipedia, "Diffie-Hellman key exchange", fetched 2026-09-21: "two parties arrive at a common secret key, without passing the common secret key across the public channel"). The eavesdropper sees $p$, $g$, $g^a$, $g^b$ and must find $a$ from $g^a$: the discrete logarithm problem.

The dry run: the toy runs in $U(101)$ with $g = 3$, the primitive root chapter 16 pinned (order exactly 100, $3^50 equiv 100 equiv -1$ halfway).

+ Alice draws $a = 27$ and posts $A = 3^27 mod 101 = 90$. Bob draws $b = 71$ and posts $B = 3^71 mod 101 = 51$.
+ Alice computes $B^27 = 48$. Bob computes $A^71 = 48$. Both match $3^(27 dot 71) = 3^1917 = 48$: one shared secret, never transmitted.
+ The attack is the log: multiply 3 into itself until 90 appears, and you hit it after exactly 27 multiplications, recovering Alice. Bob's 51 falls after 71. Two dozen lines of brute force, and that is the point.

#listing("math/samples/src/Ch17/actions.c", first: 263, last: 290, caption: [actions.c, the toy exchange over u(101) with the shared secret agreeing from both sides, then both discrete logs recovered by brute force in 27 and 71 multiplies])

#callout("warning", "101 is a teaching modulus, not a prime for practice", [
  real exchanges use primes of hundreds of digits where the 100-step ladder is $10^300$ steps and brute force is dead, and then beating it needs real algorithms: baby-step giant-step and the index calculus, which are chapter material of #xref-to("dsa", "numtheory2"). the structure here, why $g^a$ lives in a cyclic group and why $g^(a b)$ agrees from both sides, is what those algorithms attack. never build crypto from a textbook toy.
])

#diagram([the exchange: secrets 27 and 71 never cross the public line, the powers 90 and 51 do, and 48 emerges on both sides], length: 13pt, {
  cdraw.rect((0.4, 3.0), (4.8, 5.6), fill: luma(235), radius: 0.02, stroke: luma(100))
  cdraw.content((2.6, 5.15), [alice], size: 6.5pt)
  cdraw.content((2.6, 4.6), [a = 27], size: 6pt)
  cdraw.content((2.6, 4.0), [A = 3^27 = 90], size: 6pt)
  cdraw.content((2.6, 3.4), [B^27 = 48], size: 6pt)
  cdraw.rect((9.0, 3.0), (13.4, 5.6), fill: luma(235), radius: 0.02, stroke: luma(100))
  cdraw.content((11.2, 5.15), [bob], size: 6.5pt)
  cdraw.content((11.2, 4.6), [b = 71], size: 6pt)
  cdraw.content((11.2, 4.0), [B = 3^71 = 51], size: 6pt)
  cdraw.content((11.2, 3.4), [A^71 = 48], size: 6pt)
  cdraw.line((4.8, 4.3), (9.0, 4.3), stroke: (paint: luma(150), dash: "dashed"))
  cdraw.content((6.9, 4.65), [public channel], size: 6pt)
  cdraw.line((4.8, 5.4), (9.0, 5.4), stroke: luma(60), mark: (end: ">"))
  cdraw.content((6.9, 5.75), [A = 90 travels], size: 6pt)
  cdraw.line((9.0, 3.2), (4.8, 3.2), stroke: luma(60), mark: (end: ">"))
  cdraw.content((6.9, 2.85), [B = 51 travels back], size: 6pt)
  cdraw.content((6.9, 1.8), [public forever: p = 101, g = 3], size: 6pt)
  cdraw.content((6.9, 0.8), [eavesdropper: log_3 90 costs 27 multiplies], size: 6pt)
})

Chapter 16 asked what a group is; this chapter asked what groups do to each other and to sets: maps preserving tables, quotients by normal subgroups, products with lcm arithmetic, fields from polynomial quotients, actions with orbits and stabilizers, and one cyclic group whose logarithm prices a protocol. #xref-to("math", "probability") leaves determinism behind next, carrying the counting habits built here straight into it.

sources: no mml mapping exists for this chapter's material, so it was authored from canonical texts by name and four fetched pages. Dummit and Foote, Abstract Algebra, 3rd ed 2004, chs 1-3 for groups, homomorphisms, quotient groups, and the isomorphism theorems, ch 4 group actions, ch 5 direct products, ch 7 ring basics, ch 9 polynomial rings, and sec 14.3 finite fields, cited by name. Artin, Algebra, 2nd ed 2011, ch 2 for homomorphisms and cosets, the symmetry chapters for the dihedral groups, and ch 10 rings, cited by name. Wikipedia, quotient group, en.wikipedia.org/wiki/Quotient\_group, the normal subgroup criterion aN = Na, fetched 2026-09-21. Wikipedia, finite field, en.wikipedia.org/wiki/Finite\_field, nonzero elements forming a cyclic multiplicative group and the discrete log phrasing, fetched 2026-09-21. Wikipedia, Burnside's lemma, en.wikipedia.org/wiki/Burnside%27s\_lemma, the orbit count as the average of fixed points, fetched 2026-09-21. Wikipedia, Diffie-Hellman key exchange, en.wikipedia.org/wiki/Diffie%E2%80%93Hellman\_key\_exchange, the shared secret over a public channel, fetched 2026-09-21. Expected values computed with python exact integers in the one-off playground/math-ch17/gen.py, including brute-force orbit enumeration cross-checks of every Burnside count. Sample behavior verified by `pwsh -NoProfile -File tools/run-c-samples.ps1 -SampleRoot books/math/samples/src -Chapter Ch17`, 61 checks in chapter 17 of the math suite, probed on this machine 2026-09-22.
