// book 10 manifest: chapter registry used by cross references and stubs
#let icpc = (
  num: 10,
  volume: false,
  title: "the icpc world finals",
  meta: (
    title: "the icpc world finals",
    subtitle: "six finals, seven languages, first principles",
    author: "Raeliosol",
    version: "5.0",
    volume-label: "book 10",
  ),
  chapters: (
    (id: "contest", num: 1, title: "the contest and the house rules"),
    (id: "toolbox-c", num: 2, title: "the c toolbox"),
    (id: "toolbox-go", num: 3, title: "the go toolbox"),
    (id: "toolbox-java", num: 4, title: "the java toolbox"),
    (id: "toolbox-cs", num: 5, title: "the c# toolbox"),
    (id: "toolbox-js", num: 6, title: "the javascript toolbox"),
    (id: "toolbox-py", num: 7, title: "the python toolbox"),
    (id: "toolbox-lua", num: 8, title: "the lua toolbox"),
    (id: "y2017", num: 9, title: "icpc world finals 2017"),
    (id: "y2018", num: 10, title: "icpc world finals 2018"),
    (id: "y2019", num: 11, title: "icpc world finals 2019"),
    (id: "y2022", num: 12, title: "icpc world finals 2022"),
    (id: "y2023", num: 13, title: "icpc world finals 2023"),
    (id: "y2025", num: 14, title: "icpc world finals 2025"),
    (id: "fastarith", num: 15, title: "fast big arithmetic"),
  ),
)
